from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[4]
SCHEMA_PATH = ROOT / "contracts" / "artifactOwnership.schema.json"
OWNERS_PATH = ROOT / "contracts" / "artifactOwners.yml"
PYTHON_PATH = ROOT / "src" / "codaro" / "generatedContracts" / "artifactOwnership.py"
PYTHON_INIT_PATH = ROOT / "src" / "codaro" / "generatedContracts" / "__init__.py"
PACKAGED_SCHEMA_PATH = ROOT / "src" / "codaro" / "generatedContracts" / "artifactOwnership.schema.json"
TYPESCRIPT_PATH = ROOT / "editor" / "src" / "lib" / "generatedContracts" / "artifactOwnership.ts"
RUST_PATH = ROOT / "launcher" / "codaro-launcher" / "src" / "generated_contracts" / "artifact_ownership.rs"
RUST_MOD_PATH = ROOT / "launcher" / "codaro-launcher" / "src" / "generated_contracts" / "mod.rs"
ROLE_VALUES = ("source", "generated", "packaged", "evidence")


class ContractGenerationError(ValueError):
    pass


def sha256Bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def loadSources() -> tuple[dict[str, Any], dict[str, Any], str, str]:
    try:
        schemaBytes = SCHEMA_PATH.read_bytes()
        schema = json.loads(schemaBytes.decode("utf-8"))
        ownersBytes = OWNERS_PATH.read_bytes()
        owners = yaml.safe_load(ownersBytes.decode("utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError, yaml.YAMLError) as exc:
        raise ContractGenerationError(f"cannot read product contract sources: {exc}") from exc
    if not isinstance(schema, dict) or not isinstance(owners, dict):
        raise ContractGenerationError("contract sources must be mappings")
    validateSchema(schema)
    validateOwners(owners)
    return schema, owners, sha256Bytes(schemaBytes), sha256Bytes(ownersBytes)


def validateSchema(schema: dict[str, Any]) -> None:
    definitions = schema.get("$defs")
    if not isinstance(definitions, dict):
        raise ContractGenerationError("artifact ownership schema needs $defs")
    role = definitions.get("ArtifactRole")
    owner = definitions.get("ArtifactOwner")
    if not isinstance(role, dict) or tuple(role.get("enum", ())) != ROLE_VALUES:
        raise ContractGenerationError("ArtifactRole enum is not canonical")
    if not isinstance(owner, dict) or owner.get("additionalProperties") is not False:
        raise ContractGenerationError("ArtifactOwner must be a closed object")
    required = owner.get("required")
    expected = {"artifactId", "role", "owner", "sourcePath", "surfacePaths"}
    if not isinstance(required, list) or set(required) != expected:
        raise ContractGenerationError("ArtifactOwner required fields are not canonical")


def validateOwners(payload: dict[str, Any]) -> None:
    if set(payload) != {"schemaVersion", "artifacts"} or payload.get("schemaVersion") != 1:
        raise ContractGenerationError("artifactOwners.yml schemaVersion or fields are invalid")
    artifacts = payload.get("artifacts")
    if not isinstance(artifacts, list) or not artifacts:
        raise ContractGenerationError("artifactOwners.yml needs at least one artifact")
    artifactIds: set[str] = set()
    sourcePaths: set[str] = set()
    for index, artifact in enumerate(artifacts):
        if not isinstance(artifact, dict):
            raise ContractGenerationError(f"artifacts[{index}] must be a mapping")
        if set(artifact) != {"artifactId", "role", "owner", "sourcePath", "surfacePaths"}:
            raise ContractGenerationError(f"artifacts[{index}] fields are invalid")
        artifactId = artifact.get("artifactId")
        sourcePath = artifact.get("sourcePath")
        if not isinstance(artifactId, str) or not artifactId or artifactId in artifactIds:
            raise ContractGenerationError(f"artifacts[{index}].artifactId is missing or duplicate")
        if artifact.get("role") not in ROLE_VALUES:
            raise ContractGenerationError(f"artifacts[{index}].role is invalid")
        if not isinstance(sourcePath, str) or sourcePath in sourcePaths or not (ROOT / sourcePath).is_file():
            raise ContractGenerationError(f"artifacts[{index}].sourcePath is missing or duplicate")
        surfacePaths = artifact.get("surfacePaths")
        if not isinstance(surfacePaths, list) or not surfacePaths or len(surfacePaths) != len(set(surfacePaths)):
            raise ContractGenerationError(f"artifacts[{index}].surfacePaths are invalid")
        artifactIds.add(artifactId)
        sourcePaths.add(sourcePath)


def generatedHeader(schemaHash: str, ownersHash: str, comment: str) -> str:
    return (
        f"{comment} Generated by docs/skills/ops/tools/genProductContracts.py.\n"
        f"{comment} Source SHA-256: {schemaHash}\n"
        f"{comment} Owners SHA-256: {ownersHash}\n"
    )


def pythonSource(schemaHash: str, ownersHash: str) -> str:
    return generatedHeader(schemaHash, ownersHash, "#") + f'''from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


ARTIFACT_OWNERSHIP_CONTRACT_SHA256 = "{schemaHash}"
ARTIFACT_OWNERSHIP_OWNERS_SHA256 = "{ownersHash}"
ArtifactRole = Literal["source", "generated", "packaged", "evidence"]


@dataclass(frozen=True)
class ArtifactOwner:
    artifactId: str
    role: ArtifactRole
    owner: str
    sourcePath: str
    surfacePaths: tuple[str, ...]
'''


def pythonInitSource(schemaHash: str, ownersHash: str) -> str:
    return generatedHeader(schemaHash, ownersHash, "#") + '''from .artifactOwnership import (
    ARTIFACT_OWNERSHIP_CONTRACT_SHA256,
    ARTIFACT_OWNERSHIP_OWNERS_SHA256,
    ArtifactOwner,
    ArtifactRole,
)

__all__ = [
    "ARTIFACT_OWNERSHIP_CONTRACT_SHA256",
    "ARTIFACT_OWNERSHIP_OWNERS_SHA256",
    "ArtifactOwner",
    "ArtifactRole",
]
'''


def typeScriptSource(schemaHash: str, ownersHash: str) -> str:
    return generatedHeader(schemaHash, ownersHash, "//") + f'''export const ARTIFACT_OWNERSHIP_CONTRACT_SHA256 = "{schemaHash}" as const;
export const ARTIFACT_OWNERSHIP_OWNERS_SHA256 = "{ownersHash}" as const;

export type ArtifactRole = "source" | "generated" | "packaged" | "evidence";

export type ArtifactOwner = {{
  artifactId: string;
  role: ArtifactRole;
  owner: string;
  sourcePath: string;
  surfacePaths: string[];
}};
'''


def rustSource(schemaHash: str, ownersHash: str) -> str:
    return generatedHeader(schemaHash, ownersHash, "//") + f'''use serde::{{Deserialize, Serialize}};

pub const ARTIFACT_OWNERSHIP_CONTRACT_SHA256: &str = "{schemaHash}";
pub const ARTIFACT_OWNERSHIP_OWNERS_SHA256: &str = "{ownersHash}";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum ArtifactRole {{
    Source,
    Generated,
    Packaged,
    Evidence,
}}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ArtifactOwner {{
    pub artifact_id: String,
    pub role: ArtifactRole,
    pub owner: String,
    pub source_path: String,
    pub surface_paths: Vec<String>,
}}
'''


def rustModSource(schemaHash: str, ownersHash: str) -> str:
    return generatedHeader(schemaHash, ownersHash, "//") + "pub mod artifact_ownership;\n"


def expectedOutputs() -> dict[Path, str]:
    _schema, _owners, schemaHash, ownersHash = loadSources()
    return {
        PYTHON_PATH: pythonSource(schemaHash, ownersHash),
        PYTHON_INIT_PATH: pythonInitSource(schemaHash, ownersHash),
        PACKAGED_SCHEMA_PATH: SCHEMA_PATH.read_text(encoding="utf-8"),
        TYPESCRIPT_PATH: typeScriptSource(schemaHash, ownersHash),
        RUST_PATH: rustSource(schemaHash, ownersHash),
        RUST_MOD_PATH: rustModSource(schemaHash, ownersHash),
    }


def generate(*, check: bool) -> list[str]:
    stale: list[str] = []
    for path, expected in expectedOutputs().items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == expected:
            continue
        stale.append(path.relative_to(ROOT).as_posix())
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8", newline="\n")
    return stale


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate shared product contract types for all runtime surfaces.")
    parser.add_argument("--check", action="store_true", help="Fail when generated product contracts are stale.")
    args = parser.parse_args(argv)
    try:
        stale = generate(check=args.check)
    except ContractGenerationError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1
    if args.check and stale:
        print("FAIL: generated product contracts are stale", file=sys.stderr)
        for path in stale:
            print(f"  - {path}", file=sys.stderr)
        return 1
    action = "checked" if args.check else "generated"
    print(f"ok: product contracts {action} ({len(expectedOutputs())} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
