"""outputDescriptor의 UI/컨테이너 타입을 React 측 widget descriptor 타입 정의로 export.

생성물:
- editor/src/lib/widgetTypes.generated.ts

`tests/run.py gate widget-bridge`가 이 스크립트를 호출해 generated 파일이 source와 일치하는지
확인할 수 있다. --check 모드로 diff 검증.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT / "src"))

from codaro.outputDescriptor import DESCRIPTOR_TYPES, UI_COMPONENTS

OUTPUT = ROOT / "editor" / "src" / "lib" / "widgetTypes.generated.ts"

HEADER = """// AUTOGENERATED by docs/skills/ops/tools/genWidgetTypes.py — do not edit by hand.
"""


def render() -> str:
    uiUnion = " | ".join(f'"{name}"' for name in sorted(UI_COMPONENTS))
    descriptorUnion = " | ".join(f'"{name}"' for name in sorted(DESCRIPTOR_TYPES))
    return (
        HEADER
        + "\n"
        + f"export type WidgetUiComponent = {uiUnion};\n\n"
        + f"export type WidgetDescriptorType = {descriptorUnion};\n\n"
        + "export const WIDGET_UI_COMPONENTS: ReadonlyArray<WidgetUiComponent> = [\n"
        + "".join(f'  "{name}",\n' for name in sorted(UI_COMPONENTS))
        + "];\n\n"
        + "export const WIDGET_DESCRIPTOR_TYPES: ReadonlyArray<WidgetDescriptorType> = [\n"
        + "".join(f'  "{name}",\n' for name in sorted(DESCRIPTOR_TYPES))
        + "];\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate widget TS types from outputDescriptor SSOT.")
    parser.add_argument("--check", action="store_true", help="fail if generated file is out of date")
    args = parser.parse_args(argv)

    content = render()
    if args.check:
        if not OUTPUT.exists():
            print(f"FAIL: {OUTPUT} is missing", file=sys.stderr)
            return 1
        if OUTPUT.read_text(encoding="utf-8") != content:
            print(f"FAIL: {OUTPUT} is out of date — re-run without --check", file=sys.stderr)
            return 1
        print("ok: widget types up to date")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
