"""editor 빌드 산출물의 PWA 자산 정적 검증.

Lighthouse v12+ 에서 PWA category가 제거되어, 같은 신호를 정적 검증으로 대체한다.
manifest 필수 필드, workbox precache, network-first/cache-first 분기 존재 여부.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "src" / "codaro" / "webBuild"


def main() -> int:
    failures: list[str] = []

    indexHtml = BUILD / "index.html"
    if not indexHtml.is_file():
        failures.append("webBuild/index.html missing — run 'npm run build' in editor/")
        print("\n".join(f"FAIL: {item}" for item in failures), file=sys.stderr)
        return 1

    html = indexHtml.read_text(encoding="utf-8")
    if "manifest.webmanifest" not in html and "manifest.json" not in html:
        failures.append("index.html missing manifest link")
    for fragment in ('"theme-color"', "viewport-fit=cover"):
        if fragment not in html and fragment.replace('"', "") not in html:
            failures.append(f"index.html missing {fragment}")
    if "serviceWorker" not in html and "registerSW" not in html:
        failures.append("index.html missing service worker registration")

    manifestPath = BUILD / "manifest.webmanifest"
    if not manifestPath.is_file():
        manifestPath = BUILD / "manifest.json"
    if not manifestPath.is_file():
        failures.append("manifest.webmanifest/json missing in build output")
    else:
        manifest = json.loads(manifestPath.read_text(encoding="utf-8"))
        for key in ("name", "short_name", "start_url", "display", "icons", "theme_color"):
            if key not in manifest:
                failures.append(f"manifest missing key: {key}")
        if manifest.get("display") not in ("standalone", "minimal-ui", "fullscreen"):
            failures.append(f"manifest display must be installable; got {manifest.get('display')!r}")
        if not manifest.get("icons"):
            failures.append("manifest icons[] empty")

    swCandidates = list(BUILD.glob("sw.js")) + list(BUILD.glob("serviceWorker.js"))
    if not swCandidates:
        failures.append("no service worker (sw.js / serviceWorker.js) in build output")
    workboxFiles = list(BUILD.glob("workbox-*.js"))
    if not workboxFiles:
        failures.append("workbox runtime not generated by vite-plugin-pwa")

    if swCandidates:
        swText = swCandidates[0].read_text(encoding="utf-8", errors="replace")
        precacheMatch = re.search(r"precache(?:And)?Routes?\s*\(\s*(?:JSON\.parse\([^)]*\)|self\.__WB_MANIFEST|[^)]+)\)", swText)
        if not precacheMatch:
            failures.append("sw.js missing precacheRoutes/__WB_MANIFEST registration")

    if failures:
        for failure in failures:
            print(f"FAIL: {failure}", file=sys.stderr)
        return 1
    print(f"ok: PWA artifacts valid ({manifestPath.name}, sw={swCandidates[0].name}, workbox={workboxFiles[0].name})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
