// AUTOGENERATED by docs/skills/ops/tools/genWidgetTypes.py — do not edit by hand.

export type WidgetUiComponent = "button" | "checkbox" | "code_editor" | "date" | "dropdown" | "file" | "form" | "multiselect" | "number" | "progress" | "radio" | "slider" | "table" | "text" | "textarea" | "toggle";

export type WidgetDescriptorType = "accordion" | "callout" | "custom" | "hstack" | "html" | "markdown" | "plain" | "sidebar" | "stat" | "tabs" | "text" | "ui" | "vstack";

export const WIDGET_UI_COMPONENTS: ReadonlyArray<WidgetUiComponent> = [
  "button",
  "checkbox",
  "code_editor",
  "date",
  "dropdown",
  "file",
  "form",
  "multiselect",
  "number",
  "progress",
  "radio",
  "slider",
  "table",
  "text",
  "textarea",
  "toggle",
];

export const WIDGET_DESCRIPTOR_TYPES: ReadonlyArray<WidgetDescriptorType> = [
  "accordion",
  "callout",
  "custom",
  "hstack",
  "html",
  "markdown",
  "plain",
  "sidebar",
  "stat",
  "tabs",
  "text",
  "ui",
  "vstack",
];
