# Generated by docs/skills/ops/tools/genProductContracts.py.
# Source SHA-256: 4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113
# Owners SHA-256: ac8031dd9d74489afae8f755033c66df5820500e36b65271a302c8105a68eb54
from .artifactOwnership import (
    ARTIFACT_OWNERSHIP_CONTRACT_SHA256,
    ARTIFACT_OWNERSHIP_OWNERS_SHA256,
    ArtifactOwner,
    ArtifactRole,
)

__all__ = [
    "ARTIFACT_OWNERSHIP_CONTRACT_SHA256",
    "ARTIFACT_OWNERSHIP_OWNERS_SHA256",
    "ArtifactOwner",
    "ArtifactRole",
]
