# Generated by docs/skills/ops/tools/genProductContracts.py.
# Source SHA-256: 94177a1c0d471293bae2a11281cfc5ee02f3a209447b82038243c38926cf38f2
# Owners SHA-256: 7b81c9e27e40f62fe590756443bffea2c296754ecc369203b4a75c2d6dabe972
from typing import Literal, TypedDict


APP_SPEC_CONTRACT_SHA256 = "94177a1c0d471293bae2a11281cfc5ee02f3a209447b82038243c38926cf38f2"
APP_LAYOUTS = ("notebook", "learning", "stack", "grid")
APP_STATE_POLICIES = ("none", "perSession", "shared")
AppLayout = Literal["notebook", "learning", "stack", "grid"]
AppStatePolicy = Literal["none", "perSession", "shared"]


class AppSpec(TypedDict):
    schemaVersion: Literal[1]
    title: str
    layout: AppLayout
    hideCode: bool
    entryBlockIds: list[str]
    statePolicy: AppStatePolicy
