# Generated by docs/skills/ops/tools/genProductContracts.py.
# Source SHA-256: 94177a1c0d471293bae2a11281cfc5ee02f3a209447b82038243c38926cf38f2
# Owners SHA-256: 34ee8f75e20a49263f5f1aea90cf53a4391987f76b3a6046193d373a2b15cf32
from typing import Literal, TypedDict


APP_SPEC_CONTRACT_SHA256 = "94177a1c0d471293bae2a11281cfc5ee02f3a209447b82038243c38926cf38f2"
APP_LAYOUTS = ("notebook", "learning", "stack", "grid")
APP_STATE_POLICIES = ("none", "perSession", "shared")
AppLayout = Literal["notebook", "learning", "stack", "grid"]
AppStatePolicy = Literal["none", "perSession", "shared"]


class AppSpec(TypedDict):
    schemaVersion: Literal[1]
    title: str
    layout: AppLayout
    hideCode: bool
    entryBlockIds: list[str]
    statePolicy: AppStatePolicy
