# Generated by docs/skills/ops/tools/genProductContracts.py.
# Source SHA-256: 4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113
# Owners SHA-256: 34ee8f75e20a49263f5f1aea90cf53a4391987f76b3a6046193d373a2b15cf32
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


ARTIFACT_OWNERSHIP_CONTRACT_SHA256 = "4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113"
ARTIFACT_OWNERSHIP_OWNERS_SHA256 = "34ee8f75e20a49263f5f1aea90cf53a4391987f76b3a6046193d373a2b15cf32"
ArtifactRole = Literal["source", "generated", "packaged", "evidence"]


@dataclass(frozen=True)
class ArtifactOwner:
    artifactId: str
    role: ArtifactRole
    owner: str
    sourcePath: str
    surfacePaths: tuple[str, ...]
