# Generated by docs/skills/ops/tools/genProductContracts.py.
# Source SHA-256: 4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113
# Owners SHA-256: eb4f5781e730dde1767c512c26f66b592da714f44596076139075353ffa15d67
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


ARTIFACT_OWNERSHIP_CONTRACT_SHA256 = "4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113"
ARTIFACT_OWNERSHIP_OWNERS_SHA256 = "eb4f5781e730dde1767c512c26f66b592da714f44596076139075353ffa15d67"
ArtifactRole = Literal["source", "generated", "packaged", "evidence"]


@dataclass(frozen=True)
class ArtifactOwner:
    artifactId: str
    role: ArtifactRole
    owner: str
    sourcePath: str
    surfacePaths: tuple[str, ...]
