# Generated by docs/skills/ops/tools/genProductContracts.py.
# Source SHA-256: 8a97f270d70f6f39b9e23d563ad18df8f20ad964de2a4f27b2cdb99ae62ab984
# Owners SHA-256: 4f97cb32a692d203e10d15bbf5b4ce9f77e7ea80a4ed79830895358eff8744c5
from typing import Literal, TypedDict

from .appSpec import AppStatePolicy


EXECUTABLE_UNIT_CONTRACT_SHA256 = "8a97f270d70f6f39b9e23d563ad18df8f20ad964de2a4f27b2cdb99ae62ab984"
RUNTIME_TARGETS = ("browser", "server", "local", "blocked")
RuntimeTarget = Literal["browser", "server", "local", "blocked"]


class SourceSpan(TypedDict):
    path: str
    startLine: int
    endLine: int


class EffectSpec(TypedDict):
    filesystemRead: list[str]
    filesystemWrite: list[str]
    networkOrigins: list[str]
    process: bool
    gui: bool
    secretRefs: list[str]


class CapabilityDiagnostic(TypedDict):
    code: str
    message: str
    severity: Literal["info", "warning", "blocked"]
    sourceSpan: SourceSpan


class ExecutableUnitSpec(TypedDict):
    schemaVersion: Literal[1]
    unitId: str
    entryBlockId: str
    dependencyBlockIds: list[str]
    inputSchema: dict[str, object]
    outputSchema: dict[str, object]
    effects: EffectSpec
    statePolicy: AppStatePolicy
    runtimeTarget: RuntimeTarget
    sourceSpan: SourceSpan
    sourceHash: str
    dependencyHash: str
    assetHashes: dict[str, str]
    checkScenarioIds: list[str]
    evidenceReceiptIds: list[str]
    diagnostics: list[CapabilityDiagnostic]
