# Generated by docs/skills/ops/tools/genProductContracts.py.
# Source SHA-256: b877c06ffaa06af1f18a655107102e3e7358508bae712caf180a40604671938a
# Owners SHA-256: 20a223f0b2dc213988aae7b717c237efd5e75131df0bbced05958c6f7abbe714
from typing import Literal, TypedDict

from .appSpec import AppStatePolicy


EXECUTABLE_UNIT_CONTRACT_SHA256 = "b877c06ffaa06af1f18a655107102e3e7358508bae712caf180a40604671938a"
RUNTIME_TARGETS = ("browser", "server", "local", "blocked")
RuntimeTarget = Literal["browser", "server", "local", "blocked"]


class SourceSpan(TypedDict):
    path: str
    startLine: int
    endLine: int


class EffectSpec(TypedDict):
    filesystemRead: list[str]
    filesystemWrite: list[str]
    networkOrigins: list[str]
    process: bool
    gui: bool
    secretRefs: list[str]


class CapabilityDiagnostic(TypedDict):
    blockId: str
    code: str
    message: str
    severity: Literal["info", "warning", "blocked"]
    sourceSpan: SourceSpan


class ExecutableUnitSpec(TypedDict):
    schemaVersion: Literal[1]
    unitId: str
    entryBlockId: str
    dependencyBlockIds: list[str]
    inputSchema: dict[str, object]
    outputSchema: dict[str, object]
    effects: EffectSpec
    statePolicy: AppStatePolicy
    runtimeTarget: RuntimeTarget
    sourceSpan: SourceSpan
    sourceHash: str
    dependencyHash: str
    assetHashes: dict[str, str]
    checkScenarioIds: list[str]
    evidenceReceiptIds: list[str]
    diagnostics: list[CapabilityDiagnostic]
