# Generated by docs/skills/ops/tools/genProductContracts.py.
# Source SHA-256: 2c8eb74b30f880390456d4c5cb6df7a535216a0db1e44980164746b3e9569c1f
# Owners SHA-256: 34ee8f75e20a49263f5f1aea90cf53a4391987f76b3a6046193d373a2b15cf32
from typing import Literal, TypedDict

from .appSpec import AppStatePolicy


EXECUTABLE_UNIT_CONTRACT_SHA256 = "2c8eb74b30f880390456d4c5cb6df7a535216a0db1e44980164746b3e9569c1f"
RUNTIME_TARGETS = ("browser", "server", "local", "blocked")
RuntimeTarget = Literal["browser", "server", "local", "blocked"]


class SourceSpan(TypedDict):
    path: str
    startLine: int
    endLine: int


class EffectSpec(TypedDict):
    filesystemRead: list[str]
    filesystemWrite: list[str]
    networkOrigins: list[str]
    process: bool
    gui: bool
    secretRefs: list[str]


class CapabilityDiagnostic(TypedDict):
    blockId: str
    code: str
    message: str
    severity: Literal["info", "warning", "blocked"]
    sourceSpan: SourceSpan


class ProofLineage(TypedDict):
    schemaVersion: Literal[1]
    kind: Literal["codaro.proof-lineage"]
    sourceRevisionReceiptId: str
    sourceBlockHash: str
    dependencyHash: str
    learningCreditIds: list[str]
    learningCheckIds: list[str]
    lineageHash: str


class ExecutableUnitSpec(TypedDict):
    schemaVersion: Literal[1]
    unitId: str
    entryBlockId: str
    dependencyBlockIds: list[str]
    inputSchema: dict[str, object]
    outputSchema: dict[str, object]
    effects: EffectSpec
    statePolicy: AppStatePolicy
    runtimeTarget: RuntimeTarget
    sourceSpan: SourceSpan
    entryBlockHash: str
    sourceFileHash: str
    sourceRevisionHash: str
    dependencyHash: str
    assetHashes: dict[str, str]
    checkScenarioIds: list[str]
    evidenceReceiptIds: list[str]
    proofLineage: ProofLineage | None
    diagnostics: list[CapabilityDiagnostic]
