# Generated by docs/skills/ops/tools/genProductContracts.py.
# Source SHA-256: 1451218b6acfafcb95bfa64866009f4d2d195df1eb5bd72ddbfedf47b1b472f2
# Owners SHA-256: 7b81c9e27e40f62fe590756443bffea2c296754ecc369203b4a75c2d6dabe972
from typing import Literal, TypedDict


PUBLICATION_MANIFEST_CONTRACT_SHA256 = "1451218b6acfafcb95bfa64866009f4d2d195df1eb5bd72ddbfedf47b1b472f2"
PublicationTarget = Literal["browser", "server", "local"]
PublicationFileRole = Literal["shell", "runtime", "document", "data", "package"]


class PublicationRuntime(TypedDict):
    pythonIndexPath: str
    pythonIntegrityPath: str
    pyprocIntegrityPath: str


class PublicationFile(TypedDict):
    path: str
    contentHash: str
    bytes: int
    role: PublicationFileRole


class PublicationAsset(TypedDict):
    sourcePath: str
    bundlePath: str
    contentHash: str


class PublicationPackage(TypedDict):
    name: str
    bundlePath: str
    contentHash: str


class PublicationManifest(TypedDict):
    schemaVersion: Literal[1]
    target: PublicationTarget
    compilerManifestHash: str
    sourceRevisionHash: str
    entryBlockIds: list[str]
    documentPath: str
    runtime: PublicationRuntime
    files: list[PublicationFile]
    dataAssets: list[PublicationAsset]
    packageAssets: list[PublicationPackage]
    manifestHash: str
