# Generated by docs/skills/ops/tools/genProductContracts.py.
# Source SHA-256: 6c2ce138cadee331caedf8a5e6524a49fb0d3130a6175beb335084bae9e7a2ec
# Owners SHA-256: 2b5c5ea00cef0dff326ad9457fd577d8d9c4e5aa48561822713f5f89b3a20273
from typing import Literal, TypedDict


PUBLICATION_MANIFEST_CONTRACT_SHA256 = "6c2ce138cadee331caedf8a5e6524a49fb0d3130a6175beb335084bae9e7a2ec"
PublicationTarget = Literal["browser", "server", "local"]
PublicationFileRole = Literal["shell", "runtime", "document", "data", "package"]


class BrowserPublicationRuntime(TypedDict):
    pythonIndexPath: str
    pythonIntegrityPath: str
    pyprocIntegrityPath: str


class ServerPublicationRuntime(TypedDict):
    kind: Literal["server"]
    pythonVersion: str
    requirementsPath: str
    permissionScopes: list[Literal["filesystem.read", "filesystem.write", "network"]]
    secretRefs: list[str]
    networkOrigins: list[str]
    statePolicy: Literal["none", "perSession", "shared"]
    policyHash: str
    maxMemoryMb: int
    maxExecutionSeconds: int


PublicationRuntime = BrowserPublicationRuntime | ServerPublicationRuntime


class PublicationFile(TypedDict):
    path: str
    contentHash: str
    bytes: int
    role: PublicationFileRole


class PublicationAsset(TypedDict):
    sourcePath: str
    bundlePath: str
    contentHash: str


class PublicationPackage(TypedDict):
    name: str
    bundlePath: str
    contentHash: str


class PublicationManifest(TypedDict):
    schemaVersion: Literal[1]
    target: PublicationTarget
    compilerManifestHash: str
    sourceRevisionHash: str
    entryBlockIds: list[str]
    documentPath: str
    runtime: PublicationRuntime
    files: list[PublicationFile]
    dataAssets: list[PublicationAsset]
    packageAssets: list[PublicationPackage]
    manifestHash: str
