# Generated by docs/skills/ops/tools/genProductContracts.py.
# Source SHA-256: bee27622ce1cfafb4263816dfb04dfcca3922297b59d796f71e020b432f5b66d
# Owners SHA-256: 34ee8f75e20a49263f5f1aea90cf53a4391987f76b3a6046193d373a2b15cf32
from typing import Literal, TypedDict


REFERENCE_PRODUCTS_CONTRACT_SHA256 = "bee27622ce1cfafb4263816dfb04dfcca3922297b59d796f71e020b432f5b66d"
REFERENCE_RUNTIME_TARGETS = ("browser", "server", "local")
REFERENCE_EMBED_MODES = ("output", "interactive", "editable")
REFERENCE_PUBLICATION_STEPS = ("build", "serve", "embed", "deploy", "rollback")
REFERENCE_CLAIM_BOUNDARIES = ("machineVerified", "notVerified")
ReferenceRuntimeTarget = Literal["browser", "server", "local"]
ReferenceEmbedMode = Literal["output", "interactive", "editable"]
ReferencePublicationStep = Literal["build", "serve", "embed", "deploy", "rollback"]
ReferenceClaimBoundary = Literal["machineVerified", "notVerified"]


class ReferenceProductJourney(TypedDict):
    plainPython: Literal[True]
    publicSdkImports: list[str]
    appProjection: Literal[True]
    embedModes: list[ReferenceEmbedMode]
    publicationSteps: list[ReferencePublicationStep]
    proofKinds: list[str]
    claimBoundary: ReferenceClaimBoundary


class ReferenceProduct(TypedDict):
    id: str
    title: str
    sourcePath: str
    runtimeTarget: ReferenceRuntimeTarget
    entryBlockIds: list[str]
    assetPaths: list[str]
    secretRefs: list[str]
    journey: ReferenceProductJourney
    claim: str


class ReferenceProductClaims(TypedDict):
    machineVerified: list[str]
    notVerified: list[str]


class ReferenceProductsManifest(TypedDict):
    schemaVersion: Literal[1]
    kind: Literal["codaro.reference-products"]
    products: list[ReferenceProduct]
    claimBoundary: ReferenceProductClaims
