// Generated by docs/skills/ops/tools/genProductContracts.py.
// Source SHA-256: 4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113
// Owners SHA-256: 34ee8f75e20a49263f5f1aea90cf53a4391987f76b3a6046193d373a2b15cf32
use serde::{Deserialize, Serialize};

pub const ARTIFACT_OWNERSHIP_CONTRACT_SHA256: &str =
    "4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113";
pub const ARTIFACT_OWNERSHIP_OWNERS_SHA256: &str =
    "34ee8f75e20a49263f5f1aea90cf53a4391987f76b3a6046193d373a2b15cf32";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum ArtifactRole {
    Source,
    Generated,
    Packaged,
    Evidence,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ArtifactOwner {
    pub artifact_id: String,
    pub role: ArtifactRole,
    pub owner: String,
    pub source_path: String,
    pub surface_paths: Vec<String>,
}
