// Generated by docs/skills/ops/tools/genProductContracts.py.
// Source SHA-256: 4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113
// Owners SHA-256: 4bd5c45f4928736c6026a0770946a8fcf60ad8a5671e2e57ba1a72a5890e6857
use serde::{Deserialize, Serialize};

pub const ARTIFACT_OWNERSHIP_CONTRACT_SHA256: &str = "4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113";
pub const ARTIFACT_OWNERSHIP_OWNERS_SHA256: &str = "4bd5c45f4928736c6026a0770946a8fcf60ad8a5671e2e57ba1a72a5890e6857";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum ArtifactRole {
    Source,
    Generated,
    Packaged,
    Evidence,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ArtifactOwner {
    pub artifact_id: String,
    pub role: ArtifactRole,
    pub owner: String,
    pub source_path: String,
    pub surface_paths: Vec<String>,
}
