// Generated by docs/skills/ops/tools/genProductContracts.py.
// Source SHA-256: 4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113
// Owners SHA-256: 20a223f0b2dc213988aae7b717c237efd5e75131df0bbced05958c6f7abbe714
use serde::{Deserialize, Serialize};

pub const ARTIFACT_OWNERSHIP_CONTRACT_SHA256: &str = "4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113";
pub const ARTIFACT_OWNERSHIP_OWNERS_SHA256: &str = "20a223f0b2dc213988aae7b717c237efd5e75131df0bbced05958c6f7abbe714";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum ArtifactRole {
    Source,
    Generated,
    Packaged,
    Evidence,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ArtifactOwner {
    pub artifact_id: String,
    pub role: ArtifactRole,
    pub owner: String,
    pub source_path: String,
    pub surface_paths: Vec<String>,
}
