// Generated by docs/skills/ops/tools/genProductContracts.py.
// Source SHA-256: 4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113
// Owners SHA-256: 2b5c5ea00cef0dff326ad9457fd577d8d9c4e5aa48561822713f5f89b3a20273
pub mod artifact_ownership;
