// Generated by docs/skills/ops/tools/genProductContracts.py.
// Source SHA-256: 4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113
// Owners SHA-256: 04385dfb69cc770d64625e9a08c574cda55771eb9838da1de26abe620cce5828
pub mod artifact_ownership;
