from __future__ import annotations

from .toolDefinitions.automation import (
    TOOL_CAPTURE_SCREEN,
    TOOL_CLICK_ELEMENT,
    TOOL_CREATE_AUTOMATION_TASK,
    TOOL_DETECT_ELEMENTS,
    TOOL_EMERGENCY_STOP,
    TOOL_FIND_ELEMENT,
    TOOL_HTTP_REQUEST,
    TOOL_PRESS_HOTKEY,
    TOOL_READ_SCREEN_TEXT,
    TOOL_RUN_AUTOMATION,
    TOOL_SEND_NOTIFICATION,
    TOOL_START_RECORDING,
    TOOL_STOP_RECORDING,
    TOOL_TYPE_TEXT,
    TOOL_VOICE_LISTEN,
    TOOL_VOICE_SPEAK,
    TOOL_WAIT_FOR,
    TOOL_WRITE_AUTOMATION_RECIPE,
)
from .toolDefinitions.curriculumOs import (
    TOOL_ANALYZE_CURRICULUM_QUALITY,
    TOOL_COMPOSE_MASTER_PLAN,
    TOOL_GET_LESSON_STATS,
    TOOL_GET_OUTCOME_MASTERY,
    TOOL_INSPECT_CURRICULUM,
    TOOL_LIST_CURRICULUM_DOMAINS,
    TOOL_LIST_CURRICULUM_GAPS,
    TOOL_MARK_OUTCOME_VALIDATED,
    TOOL_PROPOSE_CURRICULUM_DRAFT,
    TOOL_PROPOSE_KNOWLEDGE_CHECKS,
    TOOL_PROPOSE_PREDICT_PROMPTS,
    TOOL_PROPOSE_VARIATION,
    TOOL_RESOLVE_GOAL,
    TOOL_SEARCH_CURRICULA,
)
from .toolDefinitions.diagnostics import (
    TOOL_MATCH_MISCONCEPTION,
    TOOL_READ_LEARNER_STATE,
    TOOL_RECORD_PREDICTION_RESULT,
    TOOL_SUGGEST_NEXT_STEP,
)
from .toolDefinitions.learning import (
    TOOL_CREATE_GUIDE,
    TOOL_CREATE_LEARNING_CARD,
    TOOL_CREATE_NOTEBOOK_EXERCISE,
    TOOL_CREATE_QUIZ,
    TOOL_GENERATE_NOTEBOOK,
    TOOL_SPLIT_NOTEBOOK,
    TOOL_TRACK_ACHIEVEMENT,
)
from .toolDefinitions.runtime import (
    TOOL_CHECK_EXERCISE,
    TOOL_EXECUTE_REACTIVE,
    TOOL_FS_WRITE,
    TOOL_GET_VARIABLES,
    TOOL_PACKAGES_CHECK,
    TOOL_PACKAGES_INSTALL,
)
from .toolDefinitions.workbench import (
    TOOL_CELL_CALL,
    TOOL_DELETE_BLOCK,
    TOOL_GET_BLOCKS,
    TOOL_INSERT_BLOCK,
    TOOL_READ_CELLS,
    TOOL_UPDATE_BLOCK,
    TOOL_WRITE_CELL,
    TOOL_WRITE_CURRICULUM_YAML,
)
from .toolManifest import toolManifest
from .toolRegistry import ToolDef, allTools, getTool, registerTool, toolSchemas


DEFAULT_TOOLS: tuple[ToolDef, ...] = (
    TOOL_INSERT_BLOCK,
    TOOL_UPDATE_BLOCK,
    TOOL_DELETE_BLOCK,
    TOOL_EXECUTE_REACTIVE,
    TOOL_GET_VARIABLES,
    TOOL_GET_BLOCKS,
    TOOL_READ_CELLS,
    TOOL_WRITE_CELL,
    TOOL_CELL_CALL,
    TOOL_WRITE_CURRICULUM_YAML,
    TOOL_FS_WRITE,
    TOOL_PACKAGES_CHECK,
    TOOL_PACKAGES_INSTALL,
    TOOL_CHECK_EXERCISE,
    TOOL_CREATE_GUIDE,
    TOOL_CREATE_LEARNING_CARD,
    TOOL_CREATE_QUIZ,
    TOOL_CREATE_NOTEBOOK_EXERCISE,
    TOOL_TRACK_ACHIEVEMENT,
    TOOL_SPLIT_NOTEBOOK,
    TOOL_GENERATE_NOTEBOOK,
    TOOL_HTTP_REQUEST,
    TOOL_CAPTURE_SCREEN,
    TOOL_READ_SCREEN_TEXT,
    TOOL_CLICK_ELEMENT,
    TOOL_TYPE_TEXT,
    TOOL_PRESS_HOTKEY,
    TOOL_FIND_ELEMENT,
    TOOL_WAIT_FOR,
    TOOL_START_RECORDING,
    TOOL_STOP_RECORDING,
    TOOL_WRITE_AUTOMATION_RECIPE,
    TOOL_CREATE_AUTOMATION_TASK,
    TOOL_RUN_AUTOMATION,
    TOOL_DETECT_ELEMENTS,
    TOOL_VOICE_LISTEN,
    TOOL_VOICE_SPEAK,
    TOOL_SEND_NOTIFICATION,
    TOOL_EMERGENCY_STOP,
    TOOL_LIST_CURRICULUM_DOMAINS,
    TOOL_RESOLVE_GOAL,
    TOOL_SEARCH_CURRICULA,
    TOOL_COMPOSE_MASTER_PLAN,
    TOOL_INSPECT_CURRICULUM,
    TOOL_LIST_CURRICULUM_GAPS,
    TOOL_GET_OUTCOME_MASTERY,
    TOOL_MARK_OUTCOME_VALIDATED,
    TOOL_PROPOSE_CURRICULUM_DRAFT,
    TOOL_PROPOSE_KNOWLEDGE_CHECKS,
    TOOL_PROPOSE_PREDICT_PROMPTS,
    TOOL_PROPOSE_VARIATION,
    TOOL_GET_LESSON_STATS,
    TOOL_ANALYZE_CURRICULUM_QUALITY,
    TOOL_READ_LEARNER_STATE,
    TOOL_RECORD_PREDICTION_RESULT,
    TOOL_MATCH_MISCONCEPTION,
    TOOL_SUGGEST_NEXT_STEP,
)


def defaultTools() -> tuple[ToolDef, ...]:
    return DEFAULT_TOOLS


def _registerDefaultTools() -> None:
    for tool in defaultTools():
        registerTool(tool)


_registerDefaultTools()
