// generateCurriculum.js - 커리큘럼 SSOT(../../curricula/python)를 읽어
// 랜딩 학습 페이지용 인덱스(src/lib/generated/curriculum.js)를 생성한다.
// docsNav/posts 생성기와 같은 패턴. 빌드 prebuild 단계에서 돈다.
import { dirname, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { parse as parseYaml } from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CURRICULA = resolve(__dirname, "../../curricula/python");
const OUT = resolve(__dirname, "../src/lib/generated/curriculum.js");

const DOMAIN_LABELS = {
  basics: "파이썬 기초",
  dataAnalysis: "데이터 분석",
  visualization: "시각화",
  mathStatsMl: "수학 · 통계 · ML",
  imageVision: "이미지 · 비전",
  automation: "자동화",
  devLiteracy: "개발 리터러시",
  aiIntegration: "AI 통합",
};
const DOMAIN_ORDER = Object.keys(DOMAIN_LABELS);

function walkYaml(dir, acc = []) {
  for (const entry of readdirSync(dir)) {
    if (entry.startsWith("_") || entry === "__pycache__") continue;
    const full = resolve(dir, entry);
    if (statSync(full).isDirectory()) walkYaml(full, acc);
    else if ((entry.endsWith(".yaml") || entry.endsWith(".yml")) && entry !== "schema.yaml") acc.push(full);
  }
  return acc;
}

function domainOf(fileRel) {
  return fileRel.split(/[\\/]/)[0];
}

// 레슨 문서에서 첫 실행 코드(snippet)를 재귀로 찾는다. sections[].snippet 등 위치가 다양하다.
function findFirstSnippet(node, depth = 0) {
  if (!node || depth > 8) return "";
  if (Array.isArray(node)) {
    for (const item of node) {
      const found = findFirstSnippet(item, depth + 1);
      if (found) return found;
    }
    return "";
  }
  if (typeof node === "object") {
    if (typeof node.snippet === "string" && node.snippet.trim().length > 0) return node.snippet;
    for (const value of Object.values(node)) {
      const found = findFirstSnippet(value, depth + 1);
      if (found) return found;
    }
  }
  return "";
}

const files = existsSync(CURRICULA) ? walkYaml(CURRICULA) : [];
const domains = new Map();
let lessonCount = 0;

for (const file of files) {
  let doc;
  try {
    doc = parseYaml(readFileSync(file, "utf8"));
  } catch (err) {
    console.warn(`[curriculum] YAML 파싱 건너뜀: ${relative(CURRICULA, file)} (${String(err).slice(0, 80)})`);
    continue;
  }
  const meta = doc && doc.meta;
  if (!meta || !meta.id || !meta.title) continue;
  const rel = relative(CURRICULA, file);
  const domain = domainOf(rel);
  const track = meta.category || "기타";
  const lesson = {
    id: String(meta.id),
    title: String(meta.title),
    track: String(track),
    tags: Array.isArray(meta.tags) ? meta.tags.slice(0, 6).map(String) : [],
    emoji: (doc.intro && doc.intro.emoji) || "",
    direction: (doc.intro && doc.intro.direction) || (meta.seo && meta.seo.description) || "",
    slug: `${domain}/${track}/${meta.id}`,
    code: findFirstSnippet(doc).slice(0, 800),
  };
  if (!domains.has(domain)) domains.set(domain, new Map());
  const tracks = domains.get(domain);
  if (!tracks.has(track)) tracks.set(track, []);
  tracks.get(track).push(lesson);
  lessonCount += 1;
}

const tree = DOMAIN_ORDER.filter((d) => domains.has(d)).map((domain) => {
  const tracks = domains.get(domain);
  const trackList = [...tracks.entries()].map(([track, lessons]) => ({
    track,
    lessons: lessons.sort((a, b) => a.id.localeCompare(b.id, "en", { numeric: true })),
  }));
  const count = trackList.reduce((n, t) => n + t.lessons.length, 0);
  return { domain, label: DOMAIN_LABELS[domain] || domain, count, tracks: trackList };
});

const banner = "// GENERATED by scripts/generateCurriculum.js - 직접 편집 금지. SSOT=curricula/python.";
writeFileSync(
  OUT,
  `${banner}\nexport const curriculumTree = ${JSON.stringify(tree, null, 2)};\nexport const curriculumLessonCount = ${lessonCount};\n`,
);
console.log(`[curriculum] domains=${tree.length} lessons=${lessonCount} -> ${relative(resolve(__dirname, ".."), OUT)}`);
