import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptRoot = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptRoot, "..", "..");
const sourceRoot = resolve(projectRoot, "assets", "brand", "visuals", "generated");
const targetRoot = resolve(projectRoot, "landing", "static", "visuals");
const modulePath = resolve(projectRoot, "landing", "src", "lib", "generated", "visualAssetManifest.js");
const check = process.argv.includes("--check");

if (!existsSync(resolve(sourceRoot, "manifest.json"))) {
  throw new Error("Visual asset output is missing. Run assets/brand/tools/buildVisualAssets.py first.");
}

const manifest = JSON.parse(readFileSync(resolve(sourceRoot, "manifest.json"), "utf8"));
const moduleSource = `// Generated by landing/scripts/syncVisualAssets.js.\nexport const visualAssetManifest = ${JSON.stringify(manifest, null, 2)};\n`;
const failures = [];

if (check) {
  compareTree(sourceRoot, targetRoot, failures);
  if (existsSync(modulePath) && readFileSync(modulePath, "utf8") !== moduleSource) {
    failures.push("landing visual asset resolver manifest drift");
  }
  if (failures.length) throw new Error(failures.join("\n"));
  console.log(`[visual-assets] landing mirror is current; resolver ${existsSync(modulePath) ? "is current" : "is lifecycle-generated"}`);
} else {
  syncTree(sourceRoot, targetRoot);
  writeAtomic(modulePath, moduleSource);
  console.log(`[visual-assets] landing synced ${manifest.assets.length} assets`);
}

function listFiles(root) {
  if (!existsSync(root)) return [];
  const files = [];
  const visit = (directory) => {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      const path = resolve(directory, entry.name);
      if (entry.isDirectory()) visit(path);
      else if (entry.isFile()) files.push(relative(root, path).replaceAll("\\", "/"));
    }
  };
  visit(root);
  return files.sort();
}

function compareTree(source, target, failures) {
  const expected = listFiles(source);
  const actual = listFiles(target);
  for (const path of expected.filter((value) => !actual.includes(value))) failures.push(`landing missing visual: ${path}`);
  for (const path of actual.filter((value) => !expected.includes(value))) failures.push(`landing orphan visual: ${path}`);
  for (const path of expected.filter((value) => actual.includes(value))) {
    if (!readFileSync(resolve(source, path)).equals(readFileSync(resolve(target, path)))) {
      failures.push(`landing visual drift: ${path}`);
    }
  }
}

function syncTree(source, target) {
  mkdirSync(target, { recursive: true });
  const expected = listFiles(source);
  const actual = listFiles(target);
  for (const path of actual.filter((value) => !expected.includes(value))) rmSync(resolve(target, path));
  for (const path of expected) writeAtomic(resolve(target, path), readFileSync(resolve(source, path)));
}

function writeAtomic(path, value) {
  mkdirSync(dirname(path), { recursive: true });
  const temporary = `${path}.tmp`;
  writeFileSync(temporary, value);
  rmSync(path, { force: true });
  renameSync(temporary, path);
}
