// Generated by docs/skills/ops/tools/genProductContracts.py.
// Source SHA-256: 94177a1c0d471293bae2a11281cfc5ee02f3a209447b82038243c38926cf38f2
// Owners SHA-256: 2b5c5ea00cef0dff326ad9457fd577d8d9c4e5aa48561822713f5f89b3a20273
export const APP_SPEC_CONTRACT_SHA256 = "94177a1c0d471293bae2a11281cfc5ee02f3a209447b82038243c38926cf38f2" as const;
export const APP_LAYOUTS = ["notebook", "learning", "stack", "grid"] as const;
export const APP_STATE_POLICIES = ["none", "perSession", "shared"] as const;
export type AppLayout = (typeof APP_LAYOUTS)[number];
export type AppStatePolicy = (typeof APP_STATE_POLICIES)[number];

export type AppSpec = {
  schemaVersion: 1;
  title: string;
  layout: AppLayout;
  hideCode: boolean;
  entryBlockIds: string[];
  statePolicy: AppStatePolicy;
};
