// Generated by docs/skills/ops/tools/genProductContracts.py.
// Source SHA-256: 4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113
// Owners SHA-256: 20a223f0b2dc213988aae7b717c237efd5e75131df0bbced05958c6f7abbe714
export const ARTIFACT_OWNERSHIP_CONTRACT_SHA256 = "4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113" as const;
export const ARTIFACT_OWNERSHIP_OWNERS_SHA256 = "20a223f0b2dc213988aae7b717c237efd5e75131df0bbced05958c6f7abbe714" as const;

export type ArtifactRole = "source" | "generated" | "packaged" | "evidence";

export type ArtifactOwner = {
  artifactId: string;
  role: ArtifactRole;
  owner: string;
  sourcePath: string;
  surfacePaths: string[];
};
