// Generated by docs/skills/ops/tools/genProductContracts.py.
// Source SHA-256: 4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113
// Owners SHA-256: d8e5e5af995acd7032e33f5e1f9d68f8d991f40389b8a51a3ba35bee72f14222
export const ARTIFACT_OWNERSHIP_CONTRACT_SHA256 = "4679b9c14619d69672ff06da0291dd45c71b100ee6e8a0b5698fb96cd55eb113" as const;
export const ARTIFACT_OWNERSHIP_OWNERS_SHA256 = "d8e5e5af995acd7032e33f5e1f9d68f8d991f40389b8a51a3ba35bee72f14222" as const;

export type ArtifactRole = "source" | "generated" | "packaged" | "evidence";

export type ArtifactOwner = {
  artifactId: string;
  role: ArtifactRole;
  owner: string;
  sourcePath: string;
  surfacePaths: string[];
};
