// Generated by docs/skills/ops/tools/genProductContracts.py.
// Source SHA-256: 8a97f270d70f6f39b9e23d563ad18df8f20ad964de2a4f27b2cdb99ae62ab984
// Owners SHA-256: 4f97cb32a692d203e10d15bbf5b4ce9f77e7ea80a4ed79830895358eff8744c5
import type { AppStatePolicy } from "./appSpec";

export const EXECUTABLE_UNIT_CONTRACT_SHA256 = "8a97f270d70f6f39b9e23d563ad18df8f20ad964de2a4f27b2cdb99ae62ab984" as const;
export const RUNTIME_TARGETS = ["browser", "server", "local", "blocked"] as const;
export type RuntimeTarget = (typeof RUNTIME_TARGETS)[number];

export type SourceSpan = { path: string; startLine: number; endLine: number };

export type EffectSpec = {
  filesystemRead: string[];
  filesystemWrite: string[];
  networkOrigins: string[];
  process: boolean;
  gui: boolean;
  secretRefs: string[];
};

export type CapabilityDiagnostic = {
  code: string;
  message: string;
  severity: "info" | "warning" | "blocked";
  sourceSpan: SourceSpan;
};

export type ExecutableUnitSpec = {
  schemaVersion: 1;
  unitId: string;
  entryBlockId: string;
  dependencyBlockIds: string[];
  inputSchema: Record<string, unknown>;
  outputSchema: Record<string, unknown>;
  effects: EffectSpec;
  statePolicy: AppStatePolicy;
  runtimeTarget: RuntimeTarget;
  sourceSpan: SourceSpan;
  sourceHash: string;
  dependencyHash: string;
  assetHashes: Record<string, string>;
  checkScenarioIds: string[];
  evidenceReceiptIds: string[];
  diagnostics: CapabilityDiagnostic[];
};
