// Generated by docs/skills/ops/tools/genProductContracts.py.
// Source SHA-256: b877c06ffaa06af1f18a655107102e3e7358508bae712caf180a40604671938a
// Owners SHA-256: 7b81c9e27e40f62fe590756443bffea2c296754ecc369203b4a75c2d6dabe972
import type { AppStatePolicy } from "./appSpec";

export const EXECUTABLE_UNIT_CONTRACT_SHA256 = "b877c06ffaa06af1f18a655107102e3e7358508bae712caf180a40604671938a" as const;
export const RUNTIME_TARGETS = ["browser", "server", "local", "blocked"] as const;
export type RuntimeTarget = (typeof RUNTIME_TARGETS)[number];

export type SourceSpan = { path: string; startLine: number; endLine: number };

export type EffectSpec = {
  filesystemRead: string[];
  filesystemWrite: string[];
  networkOrigins: string[];
  process: boolean;
  gui: boolean;
  secretRefs: string[];
};

export type CapabilityDiagnostic = {
  blockId: string;
  code: string;
  message: string;
  severity: "info" | "warning" | "blocked";
  sourceSpan: SourceSpan;
};

export type ExecutableUnitSpec = {
  schemaVersion: 1;
  unitId: string;
  entryBlockId: string;
  dependencyBlockIds: string[];
  inputSchema: Record<string, unknown>;
  outputSchema: Record<string, unknown>;
  effects: EffectSpec;
  statePolicy: AppStatePolicy;
  runtimeTarget: RuntimeTarget;
  sourceSpan: SourceSpan;
  sourceHash: string;
  dependencyHash: string;
  assetHashes: Record<string, string>;
  checkScenarioIds: string[];
  evidenceReceiptIds: string[];
  diagnostics: CapabilityDiagnostic[];
};
