// Generated by docs/skills/ops/tools/genProductContracts.py.
// Source SHA-256: 2c8eb74b30f880390456d4c5cb6df7a535216a0db1e44980164746b3e9569c1f
// Owners SHA-256: 34ee8f75e20a49263f5f1aea90cf53a4391987f76b3a6046193d373a2b15cf32
import type { AppStatePolicy } from "./appSpec";

export const EXECUTABLE_UNIT_CONTRACT_SHA256 = "2c8eb74b30f880390456d4c5cb6df7a535216a0db1e44980164746b3e9569c1f" as const;
export const RUNTIME_TARGETS = ["browser", "server", "local", "blocked"] as const;
export type RuntimeTarget = (typeof RUNTIME_TARGETS)[number];

export type SourceSpan = { path: string; startLine: number; endLine: number };

export type EffectSpec = {
  filesystemRead: string[];
  filesystemWrite: string[];
  networkOrigins: string[];
  process: boolean;
  gui: boolean;
  secretRefs: string[];
};

export type CapabilityDiagnostic = {
  blockId: string;
  code: string;
  message: string;
  severity: "info" | "warning" | "blocked";
  sourceSpan: SourceSpan;
};

export type ProofLineage = {
  schemaVersion: 1;
  kind: "codaro.proof-lineage";
  sourceRevisionReceiptId: string;
  sourceBlockHash: string;
  dependencyHash: string;
  learningCreditIds: string[];
  learningCheckIds: string[];
  lineageHash: string;
};

export type ExecutableUnitSpec = {
  schemaVersion: 1;
  unitId: string;
  entryBlockId: string;
  dependencyBlockIds: string[];
  inputSchema: Record<string, unknown>;
  outputSchema: Record<string, unknown>;
  effects: EffectSpec;
  statePolicy: AppStatePolicy;
  runtimeTarget: RuntimeTarget;
  sourceSpan: SourceSpan;
  entryBlockHash: string;
  sourceFileHash: string;
  sourceRevisionHash: string;
  dependencyHash: string;
  assetHashes: Record<string, string>;
  checkScenarioIds: string[];
  evidenceReceiptIds: string[];
  proofLineage: ProofLineage | null;
  diagnostics: CapabilityDiagnostic[];
};
