// Generated by docs/skills/ops/tools/genProductContracts.py.
// Source SHA-256: 6c2ce138cadee331caedf8a5e6524a49fb0d3130a6175beb335084bae9e7a2ec
// Owners SHA-256: 2b5c5ea00cef0dff326ad9457fd577d8d9c4e5aa48561822713f5f89b3a20273
export const PUBLICATION_MANIFEST_CONTRACT_SHA256 = "6c2ce138cadee331caedf8a5e6524a49fb0d3130a6175beb335084bae9e7a2ec" as const;
export type PublicationTarget = "browser" | "server" | "local";
export type PublicationFileRole = "shell" | "runtime" | "document" | "data" | "package";

export type BrowserPublicationRuntime = {
  pythonIndexPath: string;
  pythonIntegrityPath: string;
  pyprocIntegrityPath: string;
};

export type ServerPublicationRuntime = {
  kind: "server";
  pythonVersion: string;
  requirementsPath: string;
  permissionScopes: Array<"filesystem.read" | "filesystem.write" | "network">;
  secretRefs: string[];
  networkOrigins: string[];
  statePolicy: "none" | "perSession" | "shared";
  policyHash: string;
  maxMemoryMb: number;
  maxExecutionSeconds: number;
};

export type PublicationRuntime = BrowserPublicationRuntime | ServerPublicationRuntime;

export type PublicationFile = {
  path: string;
  contentHash: string;
  bytes: number;
  role: PublicationFileRole;
};

export type PublicationAsset = {
  sourcePath: string;
  bundlePath: string;
  contentHash: string;
};

export type PublicationPackage = {
  name: string;
  bundlePath: string;
  contentHash: string;
};

export type PublicationManifest = {
  schemaVersion: 1;
  target: PublicationTarget;
  compilerManifestHash: string;
  sourceRevisionHash: string;
  entryBlockIds: string[];
  documentPath: string;
  runtime: PublicationRuntime;
  files: PublicationFile[];
  dataAssets: PublicationAsset[];
  packageAssets: PublicationPackage[];
  manifestHash: string;
};
