// Generated by docs/skills/ops/tools/genProductContracts.py.
// Source SHA-256: 1451218b6acfafcb95bfa64866009f4d2d195df1eb5bd72ddbfedf47b1b472f2
// Owners SHA-256: 7b81c9e27e40f62fe590756443bffea2c296754ecc369203b4a75c2d6dabe972
export const PUBLICATION_MANIFEST_CONTRACT_SHA256 = "1451218b6acfafcb95bfa64866009f4d2d195df1eb5bd72ddbfedf47b1b472f2" as const;
export type PublicationTarget = "browser" | "server" | "local";
export type PublicationFileRole = "shell" | "runtime" | "document" | "data" | "package";

export type PublicationRuntime = {
  pythonIndexPath: string;
  pythonIntegrityPath: string;
  pyprocIntegrityPath: string;
};

export type PublicationFile = {
  path: string;
  contentHash: string;
  bytes: number;
  role: PublicationFileRole;
};

export type PublicationAsset = {
  sourcePath: string;
  bundlePath: string;
  contentHash: string;
};

export type PublicationPackage = {
  name: string;
  bundlePath: string;
  contentHash: string;
};

export type PublicationManifest = {
  schemaVersion: 1;
  target: PublicationTarget;
  compilerManifestHash: string;
  sourceRevisionHash: string;
  entryBlockIds: string[];
  documentPath: string;
  runtime: PublicationRuntime;
  files: PublicationFile[];
  dataAssets: PublicationAsset[];
  packageAssets: PublicationPackage[];
  manifestHash: string;
};
