// Generated by docs/skills/ops/tools/genProductContracts.py.
// Source SHA-256: 2b53ea20e895a2ce75798bc770ce78b1cdd586cf9dfb6c950da08390f1461a48
// Owners SHA-256: 34ee8f75e20a49263f5f1aea90cf53a4391987f76b3a6046193d373a2b15cf32
export const PUBLICATION_MANIFEST_CONTRACT_SHA256 = "2b53ea20e895a2ce75798bc770ce78b1cdd586cf9dfb6c950da08390f1461a48" as const;
export type PublicationTarget = "browser" | "server" | "local";
export type PublicationFileRole = "shell" | "runtime" | "document" | "data" | "package";

export type BrowserPublicationRuntime = {
  pythonIndexPath: string;
  pythonIntegrityPath: string;
  pyprocIntegrityPath: string;
};

export type ServerPublicationRuntime = {
  kind: "server";
  pythonVersion: string;
  requirementsPath: string;
  permissionScopes: Array<"filesystem.read" | "filesystem.write" | "network">;
  secretRefs: string[];
  networkOrigins: string[];
  statePolicy: "none" | "perSession" | "shared";
  policyHash: string;
  maxMemoryMb: number;
  maxExecutionSeconds: number;
};

export type LocalPublicationRuntime = {
  kind: "local";
  pythonVersion: string;
  requirementsPath: string;
  permissionScopes: Array<"filesystem.read" | "filesystem.write" | "network" | "process.execute" | "gui.display" | "secret.read">;
  effects: Record<string, unknown>;
  secretRefs: string[];
  networkOrigins: string[];
  statePolicy: "none" | "perSession" | "shared";
  policyHash: string;
  maxMemoryMb: number;
  maxExecutionSeconds: number;
  maxChildProcesses: number;
  apiAllowlist: string[];
};

export type PublicationRuntime = BrowserPublicationRuntime | ServerPublicationRuntime | LocalPublicationRuntime;

export type PublicationFile = {
  path: string;
  contentHash: string;
  bytes: number;
  role: PublicationFileRole;
};

export type PublicationAsset = {
  sourcePath: string;
  bundlePath: string;
  contentHash: string;
};

export type PublicationPackage = {
  name: string;
  bundlePath: string;
  contentHash: string;
};

export type PublicationProofLineage = {
  schemaVersion: 1;
  kind: "codaro.proof-lineage";
  sourceRevisionReceiptId: string;
  promotionBuildArtifactReceiptId: string;
  sourceBlockHash: string;
  dependencyHash: string;
  learningCreditIds: string[];
  learningCheckIds: string[];
  lineageHash: string;
  coveredBlockIds: string[];
  verificationStatus: "verified" | "unverified";
  permissionReceiptId: string | null;
  functionalCheckReceiptId: string | null;
  operationalRunReceiptId: string | null;
  artifactHashes: string[];
};

export type PublicationProof = {
  schemaVersion: 1;
  verificationStatus: "verified" | "unverified";
  lineages: PublicationProofLineage[];
  proofHash: string;
};

export type PublicationManifest = {
  schemaVersion: 1;
  target: PublicationTarget;
  compilerManifestHash: string;
  sourceRevisionHash: string;
  entryBlockIds: string[];
  executionBlockIds: string[];
  executionProjectionHash: string;
  proof: PublicationProof;
  documentPath: string;
  runtime: PublicationRuntime;
  files: PublicationFile[];
  dataAssets: PublicationAsset[];
  packageAssets: PublicationPackage[];
  manifestHash: string;
};
