// Generated by docs/skills/ops/tools/genProductContracts.py.
// Source SHA-256: bee27622ce1cfafb4263816dfb04dfcca3922297b59d796f71e020b432f5b66d
// Owners SHA-256: 34ee8f75e20a49263f5f1aea90cf53a4391987f76b3a6046193d373a2b15cf32
export const REFERENCE_PRODUCTS_CONTRACT_SHA256 = "bee27622ce1cfafb4263816dfb04dfcca3922297b59d796f71e020b432f5b66d" as const;
export const REFERENCE_RUNTIME_TARGETS = ["browser", "server", "local"] as const;
export const REFERENCE_EMBED_MODES = ["output", "interactive", "editable"] as const;
export const REFERENCE_PUBLICATION_STEPS = ["build", "serve", "embed", "deploy", "rollback"] as const;
export const REFERENCE_CLAIM_BOUNDARIES = ["machineVerified", "notVerified"] as const;
export type ReferenceRuntimeTarget = (typeof REFERENCE_RUNTIME_TARGETS)[number];
export type ReferenceEmbedMode = (typeof REFERENCE_EMBED_MODES)[number];
export type ReferencePublicationStep = (typeof REFERENCE_PUBLICATION_STEPS)[number];
export type ReferenceClaimBoundary = (typeof REFERENCE_CLAIM_BOUNDARIES)[number];

export type ReferenceProductJourney = {
  plainPython: true;
  publicSdkImports: string[];
  appProjection: true;
  embedModes: ReferenceEmbedMode[];
  publicationSteps: ReferencePublicationStep[];
  proofKinds: string[];
  claimBoundary: ReferenceClaimBoundary;
};

export type ReferenceProduct = {
  id: string;
  title: string;
  sourcePath: string;
  runtimeTarget: ReferenceRuntimeTarget;
  entryBlockIds: string[];
  assetPaths: string[];
  secretRefs: string[];
  journey: ReferenceProductJourney;
  claim: string;
};

export type ReferenceProductClaims = {
  machineVerified: string[];
  notVerified: string[];
};

export type ReferenceProductsManifest = {
  schemaVersion: 1;
  kind: "codaro.reference-products";
  products: ReferenceProduct[];
  claimBoundary: ReferenceProductClaims;
};
