from __future__ import annotations

from .vision_common import make_vision_lesson, vision_config


def S(name: str, source: str, process: str, result: str):
    return {"source": {"action": f"validate {name} source", "evidence": source, "risk": "invalid image contract"}, "operation": {"action": f"run bounded {name} operation", "evidence": process, "risk": "unstable parameters"}, "result": {"action": f"reconcile {name} result", "evidence": result, "risk": "wrong visual inference"}}


V = vision_config
BLUEPRINTS = {
    "00": make_vision_lesson(V("opencv_runtime", "OpenCV 실행 계약", "BGR image·dtype·pixel budget를 검증한다.", ["colorOrder", "dtype", "maxPixels"], [{"id": "color-order", "field": "colorOrder", "kind": "enum", "values": ["BGR", "GRAY"]}, {"id": "dtype", "field": "dtype", "kind": "enum", "values": ["uint8", "float32"]}, {"id": "pixel-budget", "field": "maxPixels", "kind": "range", "min": 1, "max": 100000000}], {"colorOrder": "BGR", "dtype": "uint8", "maxPixels": 20000000}, {"colorOrder": "RGB", "dtype": "int64", "maxPixels": 0}, ["sourceHash", "decoder"], {"decodedPixels": 0}, {"sourceHash": "o0", "decoder": "opencv", "decodedPixels": 1000000}, {"sourceHash": "o0", "decoder": "opencv", "decodedPixels": 1000000}, {"sourceHash": "o1", "decoder": "browser", "decodedPixels": 120000000}, S("OpenCV", "decoder shape dtype", "decode trace", "reopened geometry and hash"))),
    "01": make_vision_lesson(V("opencv_structure", "이미지 구조 탐색기", "rows·cols·channels와 memory continuity를 검증한다.", ["rows", "cols", "channels", "contiguous"], [{"id": "rows", "field": "rows", "kind": "positive"}, {"id": "cols", "field": "cols", "kind": "positive"}, {"id": "channels", "field": "channels", "kind": "enum", "values": [1, 3, 4]}, {"id": "contiguous", "field": "contiguous", "kind": "enum", "values": [True, False]}], {"rows": 480, "cols": 640, "channels": 3, "contiguous": True}, {"rows": 0, "cols": -1, "channels": 2, "contiguous": "yes"}, ["sourceHash", "layout"], {"byteCount": 0}, {"sourceHash": "os1", "layout": "HWC", "byteCount": 921600}, {"sourceHash": "os1", "layout": "HWC", "byteCount": 921600}, {"sourceHash": "os2", "layout": "CHW", "byteCount": 900000}, S("image structure", "rows cols channels stride", "memory layout trace", "byte-count reconciliation"))),
    "02": make_vision_lesson(V("opencv_color", "색공간 변환기", "cv2 입력·출력 색공간과 channel 수를 검증한다.", ["inputSpace", "outputSpace", "outputChannels"], [{"id": "input-space", "field": "inputSpace", "kind": "enum", "values": ["BGR", "RGB", "GRAY", "HSV", "LAB"]}, {"id": "output-space", "field": "outputSpace", "kind": "enum", "values": ["BGR", "RGB", "GRAY", "HSV", "LAB"]}, {"id": "space-change", "field": "inputSpace", "kind": "not-equal", "other": "outputSpace"}, {"id": "output-channels", "field": "outputChannels", "kind": "enum", "values": [1, 3]}], {"inputSpace": "BGR", "outputSpace": "GRAY", "outputChannels": 1}, {"inputSpace": "RGB", "outputSpace": "RGB", "outputChannels": 4}, ["sourceHash", "conversionCode"], {"maxRoundTripError": 1}, {"sourceHash": "oc1", "conversionCode": "BGR2HSV", "maxRoundTripError": 1}, {"sourceHash": "oc1", "conversionCode": "BGR2HSV", "maxRoundTripError": 2}, {"sourceHash": "oc2", "conversionCode": "RGB2LAB", "maxRoundTripError": 20}, S("color conversion", "source color order", "conversion code trace", "channel and round-trip error"))),
    "03": make_vision_lesson(V("geometric_transform", "기하학적 변환기", "transform matrix·output size·interpolation 계약을 검증한다.", ["matrix", "outputSize", "interpolation", "borderMode"], [{"id": "matrix", "field": "matrix", "kind": "length", "value": 6}, {"id": "output-size", "field": "outputSize", "kind": "length", "value": 2}, {"id": "interpolation", "field": "interpolation", "kind": "enum", "values": ["nearest", "linear", "cubic", "area"]}, {"id": "border-mode", "field": "borderMode", "kind": "enum", "values": ["constant", "reflect", "replicate"]}], {"matrix": [1, 0, 10, 0, 1, 20], "outputSize": [640, 480], "interpolation": "linear", "borderMode": "reflect"}, {"matrix": [1, 0, 0], "outputSize": [640], "interpolation": "magic", "borderMode": "wrap"}, ["sourceHash", "transformHash"], {"validPixelRatio": 0.01}, {"sourceHash": "gt1", "transformHash": "affine-a", "validPixelRatio": 0.95}, {"sourceHash": "gt1", "transformHash": "affine-a", "validPixelRatio": 0.955}, {"sourceHash": "gt2", "transformHash": "warp-b", "validPixelRatio": 0.5}, S("geometry", "matrix output border contract", "coordinate mapping trace", "valid-pixel geometry"))),
    "04": make_vision_lesson(V("opencv_filter", "이미지 필터 랩", "filter 종류·홀수 kernel·sigma 범위를 검증한다.", ["filter", "kernelSize", "sigma"], [{"id": "filter", "field": "filter", "kind": "enum", "values": ["gaussian", "median", "bilateral"]}, {"id": "kernel", "field": "kernelSize", "kind": "odd"}, {"id": "sigma", "field": "sigma", "kind": "range", "min": 0, "max": 100}], {"filter": "gaussian", "kernelSize": 5, "sigma": 1.5}, {"filter": "box-magic", "kernelSize": 4, "sigma": 200}, ["sourceHash", "filterHash"], {"noiseStd": 0.5}, {"sourceHash": "of1", "filterHash": "g5-s15", "noiseStd": 8.0}, {"sourceHash": "of1", "filterHash": "g5-s15", "noiseStd": 8.4}, {"sourceHash": "of2", "filterHash": "bad", "noiseStd": 20.0}, S("filter", "kernel sigma contract", "convolution trace", "noise and edge preservation"))),
    "05": make_vision_lesson(V("canny_edge", "에지 검출기", "Canny low·high threshold 순서와 aperture를 검증한다.", ["lowThreshold", "highThreshold", "apertureSize", "l2Gradient"], [{"id": "low", "field": "lowThreshold", "kind": "range", "min": 0, "max": 255}, {"id": "threshold-order", "field": "lowThreshold", "kind": "ordered", "other": "highThreshold"}, {"id": "high", "field": "highThreshold", "kind": "range", "min": 1, "max": 255}, {"id": "aperture", "field": "apertureSize", "kind": "enum", "values": [3, 5, 7]}, {"id": "gradient", "field": "l2Gradient", "kind": "enum", "values": [True, False]}], {"lowThreshold": 50, "highThreshold": 150, "apertureSize": 3, "l2Gradient": True}, {"lowThreshold": 200, "highThreshold": 100, "apertureSize": 4, "l2Gradient": "yes"}, ["sourceHash", "edgeConfigHash"], {"edgePixelRatio": 0.01}, {"sourceHash": "ce1", "edgeConfigHash": "50-150", "edgePixelRatio": 0.12}, {"sourceHash": "ce1", "edgeConfigHash": "50-150", "edgePixelRatio": 0.125}, {"sourceHash": "ce2", "edgeConfigHash": "bad", "edgePixelRatio": 0.4}, S("Canny edge", "threshold and aperture", "gradient and hysteresis trace", "edge ratio and overlay"))),
    "06": make_vision_lesson(V("binary_threshold", "이진화 스튜디오", "threshold 종류·max value·block size 계약을 검증한다.", ["method", "maxValue", "blockSize"], [{"id": "method", "field": "method", "kind": "enum", "values": ["global", "otsu", "adaptive-mean", "adaptive-gaussian"]}, {"id": "max-value", "field": "maxValue", "kind": "range", "min": 1, "max": 255}, {"id": "block-size", "field": "blockSize", "kind": "odd"}], {"method": "adaptive-gaussian", "maxValue": 255, "blockSize": 11}, {"method": "unknown", "maxValue": 0, "blockSize": 10}, ["sourceHash", "thresholdConfig"], {"foregroundRatio": 0.01}, {"sourceHash": "bt1", "thresholdConfig": "adaptive-11", "foregroundRatio": 0.35}, {"sourceHash": "bt1", "thresholdConfig": "adaptive-11", "foregroundRatio": 0.355}, {"sourceHash": "bt2", "thresholdConfig": "global", "foregroundRatio": 0.8}, S("threshold", "method max block contract", "threshold selection trace", "binary values and foreground ratio"))),
    "07": make_vision_lesson(V("morphology", "모폴로지 연산기", "operation·홀수 kernel·iteration budget를 검증한다.", ["operation", "kernelSize", "iterations", "kernelShape"], [{"id": "operation", "field": "operation", "kind": "enum", "values": ["erode", "dilate", "open", "close", "gradient"]}, {"id": "kernel-size", "field": "kernelSize", "kind": "odd"}, {"id": "iterations", "field": "iterations", "kind": "range", "min": 1, "max": 20}, {"id": "kernel-shape", "field": "kernelShape", "kind": "enum", "values": ["rect", "ellipse", "cross"]}], {"operation": "close", "kernelSize": 5, "iterations": 2, "kernelShape": "ellipse"}, {"operation": "blur", "kernelSize": 4, "iterations": 0, "kernelShape": "star"}, ["sourceHash", "morphologyHash"], {"componentCount": 1}, {"sourceHash": "mo1", "morphologyHash": "close-e5-2", "componentCount": 12}, {"sourceHash": "mo1", "morphologyHash": "close-e5-2", "componentCount": 13}, {"sourceHash": "mo2", "morphologyHash": "bad", "componentCount": 30}, S("morphology", "operation kernel iterations", "binary morphology trace", "component count change"))),
    "08": make_vision_lesson(V("histogram", "히스토그램 분석기", "channel·bin·value range·mask 사용 계약을 검증한다.", ["channel", "bins", "valueRange", "masked"], [{"id": "channel", "field": "channel", "kind": "enum", "values": ["gray", "B", "G", "R", "H", "S", "V"]}, {"id": "bins", "field": "bins", "kind": "divisible", "value": 16}, {"id": "value-range", "field": "valueRange", "kind": "length", "value": 2}, {"id": "masked", "field": "masked", "kind": "enum", "values": [True, False]}], {"channel": "gray", "bins": 256, "valueRange": [0, 256], "masked": False}, {"channel": "alpha", "bins": 250, "valueRange": [0], "masked": "no"}, ["sourceHash", "histogramConfig"], {"binTotal": 0}, {"sourceHash": "hi1", "histogramConfig": "gray-256", "binTotal": 307200}, {"sourceHash": "hi1", "histogramConfig": "gray-256", "binTotal": 307200}, {"sourceHash": "hi2", "histogramConfig": "bad", "binTotal": 100000}, S("histogram", "channel bins range mask", "histogram accumulation", "bin total and distribution"))),
    "09": make_vision_lesson(V("contour", "컨투어 탐지기", "retrieval mode·approximation·면적 threshold를 검증한다.", ["retrievalMode", "approximation", "minArea", "maxContours"], [{"id": "retrieval", "field": "retrievalMode", "kind": "enum", "values": ["external", "list", "tree"]}, {"id": "approximation", "field": "approximation", "kind": "enum", "values": ["simple", "none"]}, {"id": "min-area", "field": "minArea", "kind": "range", "min": 0, "max": 100000000}, {"id": "max-contours", "field": "maxContours", "kind": "range", "min": 1, "max": 10000}], {"retrievalMode": "external", "approximation": "simple", "minArea": 100, "maxContours": 1000}, {"retrievalMode": "all-magic", "approximation": "curve", "minArea": -1, "maxContours": 0}, ["sourceHash", "contourConfig"], {"acceptedContours": 0}, {"sourceHash": "co1", "contourConfig": "ext-a100", "acceptedContours": 12}, {"sourceHash": "co1", "contourConfig": "ext-a100", "acceptedContours": 12}, {"sourceHash": "co2", "contourConfig": "tree", "acceptedContours": 50}, S("contour", "binary source and retrieval config", "hierarchy and area trace", "accepted contour geometry"))),
    "10": make_vision_lesson(V("opencv_capstone", "종합 비전 프로젝트", "pipeline 단계·pixel budget·artifact format을 검증한다.", ["steps", "maxPixels", "outputFormat", "evidenceEveryStep"], [{"id": "steps", "field": "steps", "kind": "nonempty"}, {"id": "pixel-budget", "field": "maxPixels", "kind": "range", "min": 1, "max": 100000000}, {"id": "output-format", "field": "outputFormat", "kind": "enum", "values": ["PNG", "JPEG", "JSON"]}, {"id": "evidence", "field": "evidenceEveryStep", "kind": "enum", "values": [True]}], {"steps": ["decode", "normalize", "segment", "measure", "render"], "maxPixels": 20000000, "outputFormat": "PNG", "evidenceEveryStep": True}, {"steps": [], "maxPixels": 0, "outputFormat": "RAW", "evidenceEveryStep": False}, ["sourceHash", "pipelineHash"], {"acceptedObjects": 0}, {"sourceHash": "cap1", "pipelineHash": "v1", "acceptedObjects": 24}, {"sourceHash": "cap1", "pipelineHash": "v1", "acceptedObjects": 24}, {"sourceHash": "cap2", "pipelineHash": "v2", "acceptedObjects": 80}, S("vision pipeline", "source and step DAG", "per-step artifact ledger", "object reconciliation and render"))),
}
