from __future__ import annotations

from .vision_common import make_vision_lesson, vision_config


def S(name: str, source: str, process: str, result: str):
    return {"source": {"action": f"admit {name} source", "evidence": source, "risk": "unsafe or misread image"}, "edit": {"action": f"apply bounded {name} edit", "evidence": process, "risk": "quality or geometry loss"}, "artifact": {"action": f"reopen {name} artifact", "evidence": result, "risk": "corrupt or visually wrong output"}}


V = vision_config
BLUEPRINTS = {
    "00": make_vision_lesson(V("pillow_runtime", "Pillow 이미지 artifact", "format·mode·decompression budget를 검증한다.", ["format", "mode", "maxPixels"], [{"id": "format", "field": "format", "kind": "enum", "values": ["JPEG", "PNG", "WEBP"]}, {"id": "mode", "field": "mode", "kind": "enum", "values": ["L", "RGB", "RGBA"]}, {"id": "pixel-budget", "field": "maxPixels", "kind": "range", "min": 1, "max": 100000000}], {"format": "PNG", "mode": "RGBA", "maxPixels": 20000000}, {"format": "TIFF", "mode": "CMYK", "maxPixels": 0}, ["sourceHash", "format"], {"decodedPixels": 0}, {"sourceHash": "p0", "format": "PNG", "decodedPixels": 1000000}, {"sourceHash": "p0", "format": "PNG", "decodedPixels": 1000000}, {"sourceHash": "p1", "format": "JPEG", "decodedPixels": 120000000}, S("Pillow", "format mode pixel budget", "decode and save trace", "reopened size mode hash"))),
    "01": make_vision_lesson(V("flower_inspector", "꽃 사진 탐색기", "사진 크기·mode·EXIF orientation 해석을 검증한다.", ["width", "height", "mode", "orientation"], [{"id": "width", "field": "width", "kind": "positive"}, {"id": "height", "field": "height", "kind": "positive"}, {"id": "mode", "field": "mode", "kind": "enum", "values": ["RGB", "RGBA"]}, {"id": "orientation", "field": "orientation", "kind": "range", "min": 1, "max": 8}], {"width": 1600, "height": 1200, "mode": "RGB", "orientation": 6}, {"width": 0, "height": -1, "mode": "CMYK", "orientation": 9}, ["sourceHash", "orientationApplied"], {"displayWidth": 0}, {"sourceHash": "f1", "orientationApplied": True, "displayWidth": 1200}, {"sourceHash": "f1", "orientationApplied": True, "displayWidth": 1200}, {"sourceHash": "f2", "orientationApplied": False, "displayWidth": 1600}, S("photo inspection", "dimensions mode EXIF", "orientation transpose trace", "display geometry"))),
    "02": make_vision_lesson(V("landscape_editor", "풍경 사진 편집기", "crop box·resize filter·output aspect 계약을 검증한다.", ["cropBox", "targetWidth", "targetHeight", "resample"], [{"id": "crop-box", "field": "cropBox", "kind": "length", "value": 4}, {"id": "target-width", "field": "targetWidth", "kind": "positive"}, {"id": "target-height", "field": "targetHeight", "kind": "positive"}, {"id": "resample", "field": "resample", "kind": "enum", "values": ["LANCZOS", "BICUBIC", "BILINEAR"]}], {"cropBox": [10, 20, 1010, 620], "targetWidth": 1000, "targetHeight": 600, "resample": "LANCZOS"}, {"cropBox": [0, 0], "targetWidth": 0, "targetHeight": -1, "resample": "NEAREST"}, ["sourceHash", "recipeHash"], {"outputPixels": 0}, {"sourceHash": "e1", "recipeHash": "crop-a", "outputPixels": 600000}, {"sourceHash": "e1", "recipeHash": "crop-a", "outputPixels": 600000}, {"sourceHash": "e2", "recipeHash": "crop-b", "outputPixels": 500000}, S("landscape edit", "crop and target geometry", "resample recipe", "reopened output dimensions"))),
    "03": make_vision_lesson(V("grayscale_conversion", "흑백 사진 변환기", "source mode·target L mode·alpha 처리 정책을 검증한다.", ["sourceMode", "targetMode", "alphaPolicy"], [{"id": "source-mode", "field": "sourceMode", "kind": "enum", "values": ["RGB", "RGBA"]}, {"id": "target-mode", "field": "targetMode", "kind": "enum", "values": ["L"]}, {"id": "alpha-policy", "field": "alphaPolicy", "kind": "enum", "values": ["drop", "preserve-separate"]}], {"sourceMode": "RGBA", "targetMode": "L", "alphaPolicy": "preserve-separate"}, {"sourceMode": "CMYK", "targetMode": "RGB", "alphaPolicy": "ignore"}, ["sourceHash", "targetMode"], {"meanLuma": 0.5}, {"sourceHash": "g1", "targetMode": "L", "meanLuma": 126.0}, {"sourceHash": "g1", "targetMode": "L", "meanLuma": 126.4}, {"sourceHash": "g2", "targetMode": "RGB", "meanLuma": 140.0}, S("grayscale", "mode and alpha policy", "luma conversion trace", "L-mode histogram"))),
    "04": make_vision_lesson(V("photo_filter", "사진 필터 스튜디오", "filter 종류·홀수 kernel·strength 범위를 검증한다.", ["filter", "kernelSize", "strength"], [{"id": "filter", "field": "filter", "kind": "enum", "values": ["blur", "sharpen", "detail", "edge"]}, {"id": "kernel", "field": "kernelSize", "kind": "odd"}, {"id": "strength", "field": "strength", "kind": "range", "min": 0, "max": 3}], {"filter": "sharpen", "kernelSize": 3, "strength": 1.2}, {"filter": "magic", "kernelSize": 4, "strength": 5}, ["sourceHash", "filterId"], {"edgeEnergy": 0.5}, {"sourceHash": "pf1", "filterId": "sharp-3", "edgeEnergy": 0.7}, {"sourceHash": "pf1", "filterId": "sharp-3", "edgeEnergy": 0.72}, {"sourceHash": "pf2", "filterId": "blur-4", "edgeEnergy": 0.2}, S("photo filter", "filter kernel strength", "bounded convolution recipe", "edge-energy comparison"))),
    "05": make_vision_lesson(V("brightness_contrast", "밝기·대비 조절기", "brightness·contrast factor와 clip 정책을 검증한다.", ["brightness", "contrast", "clipMode"], [{"id": "brightness", "field": "brightness", "kind": "range", "min": 0, "max": 3}, {"id": "contrast", "field": "contrast", "kind": "range", "min": 0, "max": 3}, {"id": "clip-mode", "field": "clipMode", "kind": "enum", "values": ["saturate"]}], {"brightness": 1.1, "contrast": 1.2, "clipMode": "saturate"}, {"brightness": -1, "contrast": 5, "clipMode": "wrap"}, ["sourceHash", "recipeHash"], {"clippedRatio": 0.01}, {"sourceHash": "bc1", "recipeHash": "b11-c12", "clippedRatio": 0.04}, {"sourceHash": "bc1", "recipeHash": "b11-c12", "clippedRatio": 0.045}, {"sourceHash": "bc2", "recipeHash": "bad", "clippedRatio": 0.4}, S("brightness contrast", "factors and clip policy", "enhancement trace", "histogram and clipped ratio"))),
    "06": make_vision_lesson(V("rgb_channel_analysis", "RGB 채널 분석기", "채널 순서·histogram bin·sampling 계약을 검증한다.", ["colorOrder", "bins", "sampleStride"], [{"id": "color-order", "field": "colorOrder", "kind": "enum", "values": ["RGB"]}, {"id": "bins", "field": "bins", "kind": "divisible", "value": 16}, {"id": "sample-stride", "field": "sampleStride", "kind": "range", "min": 1, "max": 64}], {"colorOrder": "RGB", "bins": 256, "sampleStride": 1}, {"colorOrder": "BGR", "bins": 250, "sampleStride": 100}, ["sourceHash", "colorOrder"], {"histogramCount": 0}, {"sourceHash": "rgb1", "colorOrder": "RGB", "histogramCount": 921600}, {"sourceHash": "rgb1", "colorOrder": "RGB", "histogramCount": 921600}, {"sourceHash": "rgb2", "colorOrder": "BGR", "histogramCount": 900000}, S("RGB analysis", "channel order bin sampling", "histogram accumulation", "bin total reconciliation"))),
    "07": make_vision_lesson(V("watermark", "워터마크 생성기", "opacity·anchor·margin·text 계약을 검증한다.", ["text", "opacity", "anchor", "margin"], [{"id": "text", "field": "text", "kind": "nonempty"}, {"id": "opacity", "field": "opacity", "kind": "unit-interval"}, {"id": "anchor", "field": "anchor", "kind": "enum", "values": ["top-left", "top-right", "bottom-left", "bottom-right", "center"]}, {"id": "margin", "field": "margin", "kind": "range", "min": 0, "max": 200}], {"text": "Codaro", "opacity": 0.35, "anchor": "bottom-right", "margin": 24}, {"text": "", "opacity": 1.5, "anchor": "outside", "margin": -1}, ["sourceHash", "watermarkId"], {"changedPixelRatio": 0.01}, {"sourceHash": "w1", "watermarkId": "wm-a", "changedPixelRatio": 0.03}, {"sourceHash": "w1", "watermarkId": "wm-a", "changedPixelRatio": 0.035}, {"sourceHash": "w2", "watermarkId": "wm-b", "changedPixelRatio": 0.3}, S("watermark", "text opacity anchor margin", "alpha composite trace", "placement and changed pixels"))),
    "08": make_vision_lesson(V("shape_art", "도형 아트 생성기", "canvas·color mode·stroke width·shape list 계약을 검증한다.", ["canvas", "mode", "strokeWidth", "shapes"], [{"id": "canvas", "field": "canvas", "kind": "length", "value": 2}, {"id": "mode", "field": "mode", "kind": "enum", "values": ["RGB", "RGBA"]}, {"id": "stroke", "field": "strokeWidth", "kind": "positive"}, {"id": "shapes", "field": "shapes", "kind": "nonempty"}], {"canvas": [800, 600], "mode": "RGBA", "strokeWidth": 4, "shapes": ["rectangle", "ellipse"]}, {"canvas": [800], "mode": "CMYK", "strokeWidth": 0, "shapes": []}, ["recipeHash", "mode"], {"paintedPixels": 0}, {"recipeHash": "art-a", "mode": "RGBA", "paintedPixels": 12000}, {"recipeHash": "art-a", "mode": "RGBA", "paintedPixels": 12000}, {"recipeHash": "art-b", "mode": "RGB", "paintedPixels": 5000}, S("shape art", "canvas and shape manifest", "ordered draw trace", "painted pixel count"))),
    "09": make_vision_lesson(V("photo_collage", "포토 콜라주 메이커", "입력 수·column·gap·cell size 계약을 검증한다.", ["imageCount", "columns", "gap", "cellSize"], [{"id": "image-count", "field": "imageCount", "kind": "range", "min": 1, "max": 100}, {"id": "columns", "field": "columns", "kind": "range", "min": 1, "max": 10}, {"id": "gap", "field": "gap", "kind": "range", "min": 0, "max": 100}, {"id": "cell-size", "field": "cellSize", "kind": "length", "value": 2}], {"imageCount": 6, "columns": 3, "gap": 12, "cellSize": [320, 240]}, {"imageCount": 0, "columns": 20, "gap": -1, "cellSize": [320]}, ["sourceSetHash", "layoutHash"], {"placedCount": 0}, {"sourceSetHash": "set1", "layoutHash": "3x2", "placedCount": 6}, {"sourceSetHash": "set1", "layoutHash": "3x2", "placedCount": 6}, {"sourceSetHash": "set2", "layoutHash": "2x2", "placedCount": 4}, S("collage", "source set and grid", "fit-and-place trace", "placement count and canvas"))),
    "10": make_vision_lesson(V("image_editor", "종합 이미지 에디터", "편집 operation DAG·output format·quality budget를 검증한다.", ["operations", "outputFormat", "quality", "maxPixels"], [{"id": "operations", "field": "operations", "kind": "nonempty"}, {"id": "output-format", "field": "outputFormat", "kind": "enum", "values": ["PNG", "JPEG", "WEBP"]}, {"id": "quality", "field": "quality", "kind": "range", "min": 1, "max": 100}, {"id": "pixel-budget", "field": "maxPixels", "kind": "range", "min": 1, "max": 100000000}], {"operations": ["orient", "crop", "enhance", "watermark"], "outputFormat": "WEBP", "quality": 88, "maxPixels": 20000000}, {"operations": [], "outputFormat": "BMP", "quality": 0, "maxPixels": 200000000}, ["sourceHash", "recipeHash"], {"outputBytes": 100}, {"sourceHash": "ed1", "recipeHash": "v1", "outputBytes": 250000}, {"sourceHash": "ed1", "recipeHash": "v1", "outputBytes": 250050}, {"sourceHash": "ed2", "recipeHash": "v2", "outputBytes": 900000}, S("image editor", "source recipe output budget", "ordered operation ledger", "reopened artifact hash and render"))),
}
