from __future__ import annotations

from .vision_common import make_vision_lesson, vision_config


def S(name: str, input_evidence: str, process_evidence: str, result_evidence: str):
    return {
        "input": {"action": f"validate {name} input contract", "evidence": input_evidence, "risk": "misinterpreted pixels"},
        "process": {"action": f"apply bounded {name} operation", "evidence": process_evidence, "risk": "silent shape or range drift"},
        "result": {"action": f"reconcile {name} result", "evidence": result_evidence, "risk": "plausible but wrong image"},
    }


V = vision_config
BLUEPRINTS = {
    "01": make_vision_lesson(V("pixel_array", "픽셀과 ndarray", "이미지 shape·dtype·channel 불변식을 검증한다.", ["shape", "dtype", "channels"], [{"id": "shape-rank", "field": "shape", "kind": "length", "value": 3}, {"id": "dtype", "field": "dtype", "kind": "enum", "values": ["uint8", "float32"]}, {"id": "channels", "field": "channels", "kind": "range", "min": 1, "max": 4}], {"shape": [480, 640, 3], "dtype": "uint8", "channels": 3}, {"shape": [480, 640], "dtype": "float64", "channels": 5}, ["sourceHash", "colorOrder"], {"pixelCount": 0}, {"sourceHash": "h1", "colorOrder": "RGB", "pixelCount": 307200}, {"sourceHash": "h1", "colorOrder": "RGB", "pixelCount": 307200}, {"sourceHash": "h2", "colorOrder": "BGR", "pixelCount": 300000}, S("pixel array", "shape dtype channel manifest", "bounded index trace", "pixel count and source hash"))),
    "02": make_vision_lesson(V("image_coordinates", "이미지 좌표계", "width·height와 x·y 범위를 혼동하지 않도록 좌표 계약을 검증한다.", ["width", "height", "x", "y", "origin"], [{"id": "width", "field": "width", "kind": "range", "min": 1, "max": 4096}, {"id": "height", "field": "height", "kind": "range", "min": 1, "max": 4096}, {"id": "x", "field": "x", "kind": "range", "min": 0, "max": 4095}, {"id": "y", "field": "y", "kind": "range", "min": 0, "max": 4095}, {"id": "origin", "field": "origin", "kind": "enum", "values": ["top-left"]}], {"width": 640, "height": 480, "x": 120, "y": 80, "origin": "top-left"}, {"width": 0, "height": 5000, "x": -1, "y": 6000, "origin": "bottom-left"}, ["sourceHash", "origin"], {"sampleValue": 0}, {"sourceHash": "c1", "origin": "top-left", "sampleValue": 127}, {"sourceHash": "c1", "origin": "top-left", "sampleValue": 127}, {"sourceHash": "c2", "origin": "bottom-left", "sampleValue": 120}, S("coordinate", "width height origin", "x-y access trace", "sample value at coordinate"))),
    "03": make_vision_lesson(V("channel_structure", "채널 구조 분해", "channel count·color order·alpha 의미를 명시한다.", ["channelCount", "colorOrder", "alphaMode"], [{"id": "channel-count", "field": "channelCount", "kind": "enum", "values": [1, 3, 4]}, {"id": "color-order", "field": "colorOrder", "kind": "enum", "values": ["GRAY", "RGB", "BGR", "RGBA", "BGRA"]}, {"id": "alpha-mode", "field": "alphaMode", "kind": "enum", "values": ["none", "straight", "premultiplied"]}], {"channelCount": 4, "colorOrder": "RGBA", "alphaMode": "straight"}, {"channelCount": 2, "colorOrder": "CMYK", "alphaMode": "unknown"}, ["sourceHash", "colorOrder"], {"channelMean": 0.5}, {"sourceHash": "ch1", "colorOrder": "RGBA", "channelMean": 128.0}, {"sourceHash": "ch1", "colorOrder": "RGBA", "channelMean": 128.2}, {"sourceHash": "ch2", "colorOrder": "BGRA", "channelMean": 140.0}, S("channel", "channel order and alpha manifest", "split-merge trace", "per-channel statistics"))),
    "04": make_vision_lesson(V("color_space", "색공간 직관", "입력·출력 색공간과 정규화 범위를 검증한다.", ["inputSpace", "outputSpace", "valueScale"], [{"id": "input-space", "field": "inputSpace", "kind": "enum", "values": ["RGB", "BGR", "HSV", "LAB", "GRAY"]}, {"id": "output-space", "field": "outputSpace", "kind": "enum", "values": ["RGB", "BGR", "HSV", "LAB", "GRAY"]}, {"id": "different-spaces", "field": "inputSpace", "kind": "not-equal", "other": "outputSpace"}, {"id": "value-scale", "field": "valueScale", "kind": "enum", "values": ["uint8-255", "float-1"]}], {"inputSpace": "BGR", "outputSpace": "HSV", "valueScale": "uint8-255"}, {"inputSpace": "RGB", "outputSpace": "RGB", "valueScale": "unknown"}, ["sourceHash", "outputSpace"], {"maxRoundTripError": 1}, {"sourceHash": "cs1", "outputSpace": "HSV", "maxRoundTripError": 1}, {"sourceHash": "cs1", "outputSpace": "HSV", "maxRoundTripError": 2}, {"sourceHash": "cs2", "outputSpace": "LAB", "maxRoundTripError": 12}, S("color-space", "source and target color spaces", "conversion parameter trace", "round-trip error"))),
    "05": make_vision_lesson(V("roi_slice", "슬라이싱과 ROI", "반개구간 ROI 좌표의 순서와 범위를 검증한다.", ["x0", "x1", "y0", "y1", "coordinateOrder"], [{"id": "x-start", "field": "x0", "kind": "range", "min": 0, "max": 4095}, {"id": "x-order", "field": "x0", "kind": "ordered", "other": "x1"}, {"id": "y-start", "field": "y0", "kind": "range", "min": 0, "max": 4095}, {"id": "y-order", "field": "y0", "kind": "ordered", "other": "y1"}, {"id": "coordinate-order", "field": "coordinateOrder", "kind": "enum", "values": ["yx"]}], {"x0": 10, "x1": 110, "y0": 20, "y1": 80, "coordinateOrder": "yx"}, {"x0": 100, "x1": 10, "y0": 80, "y1": 20, "coordinateOrder": "xy"}, ["sourceHash", "roiId"], {"area": 0}, {"sourceHash": "r1", "roiId": "face", "area": 6000}, {"sourceHash": "r1", "roiId": "face", "area": 6000}, {"sourceHash": "r2", "roiId": "background", "area": 5500}, S("ROI", "half-open coordinate box", "slice shape trace", "ROI area and identity"))),
    "06": make_vision_lesson(V("pixel_arithmetic", "픽셀 산술", "scale·bias·clip 정책을 명시해 overflow를 막는다.", ["scale", "bias", "clipMode", "workingDtype"], [{"id": "scale", "field": "scale", "kind": "range", "min": 0, "max": 4}, {"id": "bias", "field": "bias", "kind": "range", "min": -255, "max": 255}, {"id": "clip", "field": "clipMode", "kind": "enum", "values": ["saturate", "normalize"]}, {"id": "dtype", "field": "workingDtype", "kind": "enum", "values": ["float32", "int16"]}], {"scale": 1.2, "bias": 10, "clipMode": "saturate", "workingDtype": "float32"}, {"scale": 5, "bias": 300, "clipMode": "wrap", "workingDtype": "uint8"}, ["sourceHash", "clipMode"], {"clippedRatio": 0.01}, {"sourceHash": "p1", "clipMode": "saturate", "clippedRatio": 0.05}, {"sourceHash": "p1", "clipMode": "saturate", "clippedRatio": 0.055}, {"sourceHash": "p2", "clipMode": "normalize", "clippedRatio": 0.2}, S("pixel arithmetic", "scale bias dtype contract", "pre-cast range trace", "clipped pixel ratio"))),
    "07": make_vision_lesson(V("lookup_table", "룩업 테이블", "256-entry LUT와 uint8 index 계약을 검증한다.", ["values", "inputDtype", "outputDtype"], [{"id": "lut-length", "field": "values", "kind": "length", "value": 256}, {"id": "input-dtype", "field": "inputDtype", "kind": "enum", "values": ["uint8"]}, {"id": "output-dtype", "field": "outputDtype", "kind": "enum", "values": ["uint8", "float32"]}], {"values": list(range(256)), "inputDtype": "uint8", "outputDtype": "uint8"}, {"values": list(range(255)), "inputDtype": "float32", "outputDtype": "int64"}, ["sourceHash", "lutHash"], {"distinctOutputCount": 0}, {"sourceHash": "l1", "lutHash": "lut-a", "distinctOutputCount": 200}, {"sourceHash": "l1", "lutHash": "lut-a", "distinctOutputCount": 200}, {"sourceHash": "l2", "lutHash": "lut-b", "distinctOutputCount": 120}, S("lookup-table", "256-value LUT manifest", "indexed mapping trace", "distinct output count"))),
    "08": make_vision_lesson(V("image_mask", "마스크 사고", "mask shape·dtype·foreground 비율 계약을 검증한다.", ["shape", "dtype", "foregroundRatio"], [{"id": "mask-rank", "field": "shape", "kind": "length", "value": 2}, {"id": "mask-dtype", "field": "dtype", "kind": "enum", "values": ["bool", "uint8"]}, {"id": "foreground-ratio", "field": "foregroundRatio", "kind": "unit-interval"}], {"shape": [480, 640], "dtype": "bool", "foregroundRatio": 0.25}, {"shape": [480, 640, 1], "dtype": "float32", "foregroundRatio": 1.5}, ["sourceHash", "maskHash"], {"foregroundCount": 0}, {"sourceHash": "m1", "maskHash": "mask-a", "foregroundCount": 76800}, {"sourceHash": "m1", "maskHash": "mask-a", "foregroundCount": 76800}, {"sourceHash": "m2", "maskHash": "mask-b", "foregroundCount": 70000}, S("mask", "shape dtype foreground ratio", "boolean selection trace", "foreground count"))),
    "09": make_vision_lesson(V("image_statistics", "이미지 통계", "sampling·channel·percentile 계약을 검증한다.", ["sampleCount", "channelCount", "percentiles"], [{"id": "sample-count", "field": "sampleCount", "kind": "positive"}, {"id": "channel-count", "field": "channelCount", "kind": "enum", "values": [1, 3, 4]}, {"id": "percentiles", "field": "percentiles", "kind": "length", "value": 3}], {"sampleCount": 10000, "channelCount": 3, "percentiles": [5, 50, 95]}, {"sampleCount": 0, "channelCount": 2, "percentiles": [50]}, ["sourceHash", "samplingPlan"], {"meanLuma": 0.5}, {"sourceHash": "s1", "samplingPlan": "grid-10000", "meanLuma": 127.0}, {"sourceHash": "s1", "samplingPlan": "grid-10000", "meanLuma": 127.4}, {"sourceHash": "s2", "samplingPlan": "random", "meanLuma": 140.0}, S("image statistics", "sampling and percentile plan", "deterministic sample indices", "channel summary reconciliation"))),
    "10": make_vision_lesson(V("mini_correction", "미니 보정기", "gamma·contrast·white-balance 순서와 범위를 검증한다.", ["gamma", "contrast", "whiteBalance", "operationOrder"], [{"id": "gamma", "field": "gamma", "kind": "range", "min": 0.1, "max": 5}, {"id": "contrast", "field": "contrast", "kind": "range", "min": 0, "max": 3}, {"id": "white-balance", "field": "whiteBalance", "kind": "enum", "values": ["none", "gray-world"]}, {"id": "operation-order", "field": "operationOrder", "kind": "length", "value": 3}], {"gamma": 1.1, "contrast": 1.2, "whiteBalance": "gray-world", "operationOrder": ["whiteBalance", "gamma", "contrast"]}, {"gamma": 0, "contrast": 5, "whiteBalance": "auto-magic", "operationOrder": ["gamma"]}, ["sourceHash", "recipeHash"], {"meanLuma": 0.5}, {"sourceHash": "b1", "recipeHash": "rec-a", "meanLuma": 130.0}, {"sourceHash": "b1", "recipeHash": "rec-a", "meanLuma": 130.4}, {"sourceHash": "b2", "recipeHash": "rec-b", "meanLuma": 150.0}, S("correction", "ordered correction recipe", "per-step range trace", "before-after luma and recipe hash"))),
}
