from __future__ import annotations

from .vision_common import make_vision_lesson, vision_config


def S(name: str, source: str, process: str, result: str):
    return {"source": {"action": f"validate {name} frames", "evidence": source, "risk": "wrong frame identity"}, "estimate": {"action": f"estimate bounded {name}", "evidence": process, "risk": "unstable geometry"}, "verify": {"action": f"verify {name} result", "evidence": result, "risk": "confident but wrong tracking"}}


V = vision_config
BLUEPRINTS = {
    "01": make_vision_lesson(V("corner_detection", "코너 검출", "max corner·quality·minimum distance 계약을 검증한다.", ["maxCorners", "qualityLevel", "minDistance", "blockSize"], [{"id": "max-corners", "field": "maxCorners", "kind": "range", "min": 1, "max": 10000}, {"id": "quality", "field": "qualityLevel", "kind": "unit-interval"}, {"id": "distance", "field": "minDistance", "kind": "positive"}, {"id": "block", "field": "blockSize", "kind": "odd"}], {"maxCorners": 500, "qualityLevel": 0.01, "minDistance": 10, "blockSize": 3}, {"maxCorners": 0, "qualityLevel": 1.5, "minDistance": 0, "blockSize": 4}, ["sourceHash", "detectorHash"], {"cornerCount": 2}, {"sourceHash": "k1", "detectorHash": "gftt-a", "cornerCount": 120}, {"sourceHash": "k1", "detectorHash": "gftt-a", "cornerCount": 121}, {"sourceHash": "k2", "detectorHash": "bad", "cornerCount": 900}, S("corner", "gray frame and ROI", "corner score parameters", "count and spatial coverage"))),
    "02": make_vision_lesson(V("orb_features", "ORB 특징점", "feature budget·scale factor·pyramid level을 검증한다.", ["nFeatures", "scaleFactor", "nLevels", "edgeThreshold"], [{"id": "features", "field": "nFeatures", "kind": "range", "min": 1, "max": 10000}, {"id": "scale-factor", "field": "scaleFactor", "kind": "range", "min": 1.01, "max": 3}, {"id": "levels", "field": "nLevels", "kind": "range", "min": 1, "max": 32}, {"id": "edge", "field": "edgeThreshold", "kind": "range", "min": 0, "max": 100}], {"nFeatures": 1000, "scaleFactor": 1.2, "nLevels": 8, "edgeThreshold": 31}, {"nFeatures": 0, "scaleFactor": 1, "nLevels": 0, "edgeThreshold": 200}, ["sourceHash", "descriptorType"], {"descriptorCount": 2}, {"sourceHash": "orb1", "descriptorType": "ORB-256", "descriptorCount": 800}, {"sourceHash": "orb1", "descriptorType": "ORB-256", "descriptorCount": 801}, {"sourceHash": "orb2", "descriptorType": "SIFT", "descriptorCount": 200}, S("ORB", "frame pyramid contract", "keypoint descriptor trace", "descriptor count and coverage"))),
    "03": make_vision_lesson(V("feature_matching", "특징점 매칭", "descriptor norm·ratio test·cross-check 계약을 검증한다.", ["norm", "ratioThreshold", "crossCheck", "maxMatches"], [{"id": "norm", "field": "norm", "kind": "enum", "values": ["hamming", "l2"]}, {"id": "ratio", "field": "ratioThreshold", "kind": "unit-interval"}, {"id": "cross-check", "field": "crossCheck", "kind": "enum", "values": [True, False]}, {"id": "max-matches", "field": "maxMatches", "kind": "range", "min": 1, "max": 10000}], {"norm": "hamming", "ratioThreshold": 0.75, "crossCheck": False, "maxMatches": 500}, {"norm": "cosine", "ratioThreshold": 1.5, "crossCheck": "yes", "maxMatches": 0}, ["queryHash", "trainHash"], {"inlierRatio": 0.01}, {"queryHash": "q1", "trainHash": "t1", "inlierRatio": 0.7}, {"queryHash": "q1", "trainHash": "t1", "inlierRatio": 0.705}, {"queryHash": "q2", "trainHash": "t2", "inlierRatio": 0.2}, S("feature match", "descriptor identity and type", "ratio and symmetry trace", "inlier ratio and match overlay"))),
    "04": make_vision_lesson(V("homography", "호모그래피 정렬", "대응점 수·RANSAC threshold·iteration budget를 검증한다.", ["correspondenceCount", "ransacThreshold", "maxIterations", "confidence"], [{"id": "correspondences", "field": "correspondenceCount", "kind": "range", "min": 4, "max": 100000}, {"id": "ransac", "field": "ransacThreshold", "kind": "positive"}, {"id": "iterations", "field": "maxIterations", "kind": "range", "min": 1, "max": 100000}, {"id": "confidence", "field": "confidence", "kind": "unit-interval"}], {"correspondenceCount": 120, "ransacThreshold": 3.0, "maxIterations": 2000, "confidence": 0.995}, {"correspondenceCount": 3, "ransacThreshold": 0, "maxIterations": 0, "confidence": 2}, ["queryHash", "referenceHash"], {"reprojectionError": 0.1}, {"queryHash": "hq", "referenceHash": "hr", "reprojectionError": 1.5}, {"queryHash": "hq", "referenceHash": "hr", "reprojectionError": 1.55}, {"queryHash": "other", "referenceHash": "hr", "reprojectionError": 9.0}, S("homography", "point correspondence manifest", "RANSAC inlier trace", "reprojection error and warp overlay"))),
    "05": make_vision_lesson(V("panorama", "파노라마 스티칭", "image count·overlap·projection·blend 계약을 검증한다.", ["imageCount", "minimumOverlap", "projection", "blend"], [{"id": "image-count", "field": "imageCount", "kind": "range", "min": 2, "max": 100}, {"id": "overlap", "field": "minimumOverlap", "kind": "unit-interval"}, {"id": "projection", "field": "projection", "kind": "enum", "values": ["planar", "cylindrical", "spherical"]}, {"id": "blend", "field": "blend", "kind": "enum", "values": ["feather", "multiband"]}], {"imageCount": 4, "minimumOverlap": 0.25, "projection": "cylindrical", "blend": "multiband"}, {"imageCount": 1, "minimumOverlap": 1.2, "projection": "flat-magic", "blend": "none"}, ["sourceSetHash", "stitchOrderHash"], {"coverageRatio": 0.01}, {"sourceSetHash": "ps1", "stitchOrderHash": "1-2-3-4", "coverageRatio": 0.92}, {"sourceSetHash": "ps1", "stitchOrderHash": "1-2-3-4", "coverageRatio": 0.925}, {"sourceSetHash": "ps2", "stitchOrderHash": "4-1", "coverageRatio": 0.4}, S("panorama", "ordered image set and overlap", "pairwise homography ledger", "coverage and seam inspection"))),
    "06": make_vision_lesson(V("video_io", "비디오 입출력", "FPS·frame size·codec·frame budget를 검증한다.", ["fps", "frameSize", "codec", "maxFrames"], [{"id": "fps", "field": "fps", "kind": "range", "min": 0.1, "max": 240}, {"id": "frame-size", "field": "frameSize", "kind": "length", "value": 2}, {"id": "codec", "field": "codec", "kind": "enum", "values": ["mp4v", "avc1", "MJPG", "VP80"]}, {"id": "frame-budget", "field": "maxFrames", "kind": "range", "min": 1, "max": 1000000}], {"fps": 30, "frameSize": [1920, 1080], "codec": "mp4v", "maxFrames": 18000}, {"fps": 0, "frameSize": [1920], "codec": "raw", "maxFrames": 0}, ["videoHash", "codec"], {"writtenFrames": 0}, {"videoHash": "v1", "codec": "mp4v", "writtenFrames": 900}, {"videoHash": "v1", "codec": "mp4v", "writtenFrames": 900}, {"videoHash": "v2", "codec": "raw", "writtenFrames": 850}, S("video IO", "container fps frame geometry", "decode-encode counters", "reopened frame count and duration"))),
    "07": make_vision_lesson(V("background_subtraction", "배경 차분", "history·variance threshold·shadow 정책을 검증한다.", ["history", "varThreshold", "detectShadows", "warmupFrames"], [{"id": "history", "field": "history", "kind": "range", "min": 1, "max": 100000}, {"id": "variance", "field": "varThreshold", "kind": "positive"}, {"id": "shadows", "field": "detectShadows", "kind": "enum", "values": [True, False]}, {"id": "warmup", "field": "warmupFrames", "kind": "range", "min": 0, "max": 10000}], {"history": 500, "varThreshold": 16, "detectShadows": True, "warmupFrames": 60}, {"history": 0, "varThreshold": 0, "detectShadows": "yes", "warmupFrames": 20000}, ["videoHash", "backgroundModelHash"], {"foregroundRatio": 0.01}, {"videoHash": "bg1", "backgroundModelHash": "m1", "foregroundRatio": 0.08}, {"videoHash": "bg1", "backgroundModelHash": "m1", "foregroundRatio": 0.085}, {"videoHash": "bg2", "backgroundModelHash": "m2", "foregroundRatio": 0.6}, S("background model", "video and warmup contract", "model update trace", "foreground stability"))),
    "08": make_vision_lesson(V("optical_flow", "광학 흐름", "window·pyramid·termination 계약을 검증한다.", ["windowSize", "pyramidLevels", "maxIterations", "epsilon"], [{"id": "window", "field": "windowSize", "kind": "odd"}, {"id": "levels", "field": "pyramidLevels", "kind": "range", "min": 0, "max": 16}, {"id": "iterations", "field": "maxIterations", "kind": "range", "min": 1, "max": 1000}, {"id": "epsilon", "field": "epsilon", "kind": "positive"}], {"windowSize": 21, "pyramidLevels": 3, "maxIterations": 30, "epsilon": 0.01}, {"windowSize": 20, "pyramidLevels": 20, "maxIterations": 0, "epsilon": 0}, ["previousFrameHash", "currentFrameHash"], {"trackedRatio": 0.01}, {"previousFrameHash": "f1", "currentFrameHash": "f2", "trackedRatio": 0.85}, {"previousFrameHash": "f1", "currentFrameHash": "f2", "trackedRatio": 0.855}, {"previousFrameHash": "x", "currentFrameHash": "f2", "trackedRatio": 0.2}, S("optical flow", "ordered frame pair and points", "pyramid convergence trace", "tracked ratio and displacement"))),
    "09": make_vision_lesson(V("object_tracker", "객체 트래커", "tracker 종류·초기 bbox·confidence 재시작 기준을 검증한다.", ["tracker", "initialBox", "reinitializeBelow", "maxLostFrames"], [{"id": "tracker", "field": "tracker", "kind": "enum", "values": ["KCF", "CSRT", "MOSSE", "MIL"]}, {"id": "initial-box", "field": "initialBox", "kind": "length", "value": 4}, {"id": "reinit", "field": "reinitializeBelow", "kind": "unit-interval"}, {"id": "lost-budget", "field": "maxLostFrames", "kind": "range", "min": 0, "max": 1000}], {"tracker": "CSRT", "initialBox": [100, 80, 200, 160], "reinitializeBelow": 0.4, "maxLostFrames": 10}, {"tracker": "MAGIC", "initialBox": [100, 80], "reinitializeBelow": -1, "maxLostFrames": 2000}, ["videoHash", "trackId"], {"successfulFrames": 1}, {"videoHash": "tr1", "trackId": "person-1", "successfulFrames": 290}, {"videoHash": "tr1", "trackId": "person-1", "successfulFrames": 291}, {"videoHash": "tr2", "trackId": "person-2", "successfulFrames": 120}, S("tracker", "video track identity bbox", "per-frame update ledger", "success count and drift review"))),
    "10": make_vision_lesson(V("video_roi_capstone", "영상 ROI 추적기", "ROI·frame budget·evidence cadence·fallback 계약을 검증한다.", ["roi", "maxFrames", "evidenceInterval", "fallback"], [{"id": "roi", "field": "roi", "kind": "length", "value": 4}, {"id": "frame-budget", "field": "maxFrames", "kind": "range", "min": 1, "max": 1000000}, {"id": "evidence-interval", "field": "evidenceInterval", "kind": "range", "min": 1, "max": 10000}, {"id": "fallback", "field": "fallback", "kind": "enum", "values": ["redetect", "stop-and-report"]}], {"roi": [100, 80, 200, 160], "maxFrames": 1800, "evidenceInterval": 60, "fallback": "redetect"}, {"roi": [100, 80], "maxFrames": 0, "evidenceInterval": 0, "fallback": "guess"}, ["videoHash", "trackId"], {"evidenceFrames": 1}, {"videoHash": "roi1", "trackId": "asset-1", "evidenceFrames": 30}, {"videoHash": "roi1", "trackId": "asset-1", "evidenceFrames": 31}, {"videoHash": "roi2", "trackId": "asset-2", "evidenceFrames": 4}, S("ROI tracker", "video ROI and budget", "track-fallback state ledger", "sampled overlays and completion"))),
}
